# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/settings/views/ui/pomoc_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(394, 418)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.verticalGroupBox = QtWidgets.QGroupBox(Dialog)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.version_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.version_lbl.setOpenExternalLinks(False)
        self.version_lbl.setObjectName("version_lbl")
        self.horizontalLayout_3.addWidget(self.version_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_11.setOpenExternalLinks(True)
        self.label_11.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.verticalGroupBox)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(Dialog)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.verticalGroupBox1)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_13.setOpenExternalLinks(True)
        self.label_13.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.verticalGroupBox1)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.verticalGroupBox1)
        self.verticalGroupBox2 = QtWidgets.QGroupBox(Dialog)
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.verticalGroupBox2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.verticalGroupBox2)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.verticalGroupBox2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(self.verticalGroupBox2)
        self.label_18.setOpenExternalLinks(True)
        self.label_18.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.verticalGroupBox2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setEnabled(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Okno pomocy"))
        self.verticalGroupBox.setTitle(_translate("Dialog", "Informacje o wtyczce"))
        self.label_3.setText(_translate("Dialog", "Wersja wtyczki:"))
        self.version_lbl.setText(_translate("Dialog", "0.0"))
        self.label_4.setText(_translate("Dialog", "Licencja:"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><a href=\"https://www.gnu.org/licenses/gpl-3.0.html\">GNU General Public License v3.0</a></body></html>"))
        self.label.setText(_translate("Dialog", "Repozytorium kodu:"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://github.com/envirosolutionspl/wtyczka_qgis_app\"><span style=\" text-decoration: underline; color:#0000ff;\">github/envirosolutionspl</span></a></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Zgłaszanie błędów:"))
        self.label_6.setText(_translate("Dialog", "<a href=\"https://github.com/envirosolutionspl/wtyczka_qgis_app/issues\">issue tracker</a>"))
        self.label_8.setText(_translate("Dialog", "Twórca:"))
        self.label_9.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">EnviroSolutions Sp. z o.o.</a>"))
        self.label_10.setText(_translate("Dialog", "Właściciel:"))
        self.label_11.setText(_translate("Dialog", "<a href=\"https://www.gov.pl/web/rozwoj\">Ministerstwo Rozwoju</a>"))
        self.verticalGroupBox1.setTitle(_translate("Dialog", "Podstawa prawna"))
        self.label_12.setText(_translate("Dialog", "Treść rozporządzenia:"))
        self.label_13.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">link</a>"))
        self.label_15.setText(_translate("Dialog", "Katalog obiektów:"))
        self.label_14.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">link</a>"))
        self.verticalGroupBox2.setTitle(_translate("Dialog", "Materiały informacyjne"))
        self.label_17.setText(_translate("Dialog", "Filmy instruktażowe:"))
        self.label_16.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">link</a>"))
        self.label_19.setText(_translate("Dialog", "Instrukcja pisemna:"))
        self.label_18.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">link</a>"))
        self.cancel_btn.setText(_translate("Dialog", "Zamknij"))

