# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/settings/views/ui/ustawienia_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(500, 600)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.empty_lbl = QtWidgets.QLabel(Dialog)
        self.empty_lbl.setText("")
        self.empty_lbl.setObjectName("empty_lbl")
        self.verticalLayout.addWidget(self.empty_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_scrollArea = QtWidgets.QScrollArea(Dialog)
        self.settings_scrollArea.setWidgetResizable(True)
        self.settings_scrollArea.setObjectName("settings_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 476, 474))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.folder_btn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.folder_btn.setObjectName("folder_btn")
        self.verticalLayout_4.addWidget(self.folder_btn)
        self.folder_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.folder_lbl.setFont(font)
        self.folder_lbl.setText("")
        self.folder_lbl.setObjectName("folder_lbl")
        self.verticalLayout_4.addWidget(self.folder_lbl)
        self.verticalLayout_2.addWidget(self.verticalGroupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.name_lbl = QtWidgets.QLabel(self.verticalGroupBox1)
        self.name_lbl.setObjectName("name_lbl")
        self.horizontalLayout_7.addWidget(self.name_lbl)
        self.name_lineEdit = QgsFilterLineEdit(self.verticalGroupBox1)
        self.name_lineEdit.setProperty("qgisRelation", "")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout_7.addWidget(self.name_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mail_lbl = QtWidgets.QLabel(self.verticalGroupBox1)
        self.mail_lbl.setObjectName("mail_lbl")
        self.horizontalLayout_6.addWidget(self.mail_lbl)
        self.mail_lineEdit = QgsFilterLineEdit(self.verticalGroupBox1)
        self.mail_lineEdit.setProperty("qgisRelation", "")
        self.mail_lineEdit.setObjectName("mail_lineEdit")
        self.horizontalLayout_6.addWidget(self.mail_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.verticalGroupBox1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.smtp_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.smtp_btn.setObjectName("smtp_btn")
        self.horizontalLayout_3.addWidget(self.smtp_btn)
        self.csw_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.csw_btn.setObjectName("csw_btn")
        self.horizontalLayout_3.addWidget(self.csw_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.settings_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.settings_scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.exit_btn = QtWidgets.QPushButton(Dialog)
        self.exit_btn.setEnabled(True)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_2.addWidget(self.exit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Ustawienia wtyczki APP"))
        self.verticalGroupBox.setTitle(_translate("Dialog", "Domyślna ścieżka zapisu plików"))
        self.folder_btn.setText(_translate("Dialog", "Wybierz katalog"))
        self.verticalGroupBox1.setTitle(_translate("Dialog", "Domyślny punkt kontaktowy"))
        self.name_lbl.setText(_translate("Dialog", "Nazwa       "))
        self.mail_lbl.setText(_translate("Dialog", "Adres email"))
        self.smtp_btn.setText(_translate("Dialog", "Ustawienia serwera SMTP"))
        self.csw_btn.setText(_translate("Dialog", "Ustawienia serwera CSW"))
        self.save_btn.setText(_translate("Dialog", "Zapisz"))
        self.exit_btn.setText(_translate("Dialog", "Zamknij"))

from qgsfilterlineedit import QgsFilterLineEdit
