# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generowanie_gml_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(666, 394)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFile_lbl = QtWidgets.QLabel(Dialog)
        self.addFile_lbl.setObjectName("addFile_lbl")
        self.horizontalLayout.addWidget(self.addFile_lbl)
        self.addElement_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addElement_btn.setFont(font)
        self.addElement_btn.setObjectName("addElement_btn")
        self.horizontalLayout.addWidget(self.addElement_btn)
        self.deleteElement_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deleteElement_btn.setFont(font)
        self.deleteElement_btn.setObjectName("deleteElement_btn")
        self.horizontalLayout.addWidget(self.deleteElement_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.filesTable_widget = QtWidgets.QTableWidget(Dialog)
        self.filesTable_widget.setObjectName("filesTable_widget")
        self.filesTable_widget.setColumnCount(2)
        self.filesTable_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable_widget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.filesTable_widget)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.questionMakeAnotherApp_lbl = QtWidgets.QLabel(Dialog)
        self.questionMakeAnotherApp_lbl.setWordWrap(True)
        self.questionMakeAnotherApp_lbl.setObjectName("questionMakeAnotherApp_lbl")
        self.verticalLayout.addWidget(self.questionMakeAnotherApp_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yesMakeAnotherApp_radioBtn = QtWidgets.QRadioButton(Dialog)
        self.yesMakeAnotherApp_radioBtn.setChecked(True)
        self.yesMakeAnotherApp_radioBtn.setObjectName("yesMakeAnotherApp_radioBtn")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.yesMakeAnotherApp_radioBtn)
        self.horizontalLayout_2.addWidget(self.yesMakeAnotherApp_radioBtn)
        self.noMakeAnotherApp_radioBtn = QtWidgets.QRadioButton(Dialog)
        self.noMakeAnotherApp_radioBtn.setObjectName("noMakeAnotherApp_radioBtn")
        self.buttonGroup_2.addButton(self.noMakeAnotherApp_radioBtn)
        self.horizontalLayout_2.addWidget(self.noMakeAnotherApp_radioBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.questionMakeSet_lbl = QtWidgets.QLabel(Dialog)
        self.questionMakeSet_lbl.setEnabled(False)
        self.questionMakeSet_lbl.setWordWrap(True)
        self.questionMakeSet_lbl.setObjectName("questionMakeSet_lbl")
        self.verticalLayout.addWidget(self.questionMakeSet_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yesMakeSet_radioBtn = QtWidgets.QRadioButton(Dialog)
        self.yesMakeSet_radioBtn.setEnabled(False)
        self.yesMakeSet_radioBtn.setChecked(True)
        self.yesMakeSet_radioBtn.setObjectName("yesMakeSet_radioBtn")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.yesMakeSet_radioBtn)
        self.horizontalLayout_3.addWidget(self.yesMakeSet_radioBtn)
        self.noMakeSet_radioBtn = QtWidgets.QRadioButton(Dialog)
        self.noMakeSet_radioBtn.setEnabled(False)
        self.noMakeSet_radioBtn.setObjectName("noMakeSet_radioBtn")
        self.buttonGroup.addButton(self.noMakeSet_radioBtn)
        self.horizontalLayout_3.addWidget(self.noMakeSet_radioBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.empty3_lbl = QtWidgets.QLabel(Dialog)
        self.empty3_lbl.setText("")
        self.empty3_lbl.setObjectName("empty3_lbl")
        self.verticalLayout.addWidget(self.empty3_lbl)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setEnabled(True)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_4.addWidget(self.prev_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.generate_btn = QtWidgets.QPushButton(Dialog)
        self.generate_btn.setObjectName("generate_btn")
        self.horizontalLayout_4.addWidget(self.generate_btn)
        self.next_btn = QtWidgets.QPushButton(Dialog)
        self.next_btn.setEnabled(True)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_4.addWidget(self.next_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Generowanie GML dla APP"))
        self.addFile_lbl.setText(_translate("Dialog", "Lista plików na podstawie, których zostanie wygenerowany plik GML"))
        self.addElement_btn.setText(_translate("Dialog", "+"))
        self.deleteElement_btn.setText(_translate("Dialog", "-"))
        item = self.filesTable_widget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nr"))
        item = self.filesTable_widget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Pliki XML/GML"))
        self.questionMakeAnotherApp_lbl.setText(_translate("Dialog", "Czy chcesz utworzyć kolejny APP dla tego zbioru? (Tak - przycisk Dalej przeniesie do narzędzia tworzenia APP)"))
        self.yesMakeAnotherApp_radioBtn.setText(_translate("Dialog", "Tak"))
        self.noMakeAnotherApp_radioBtn.setText(_translate("Dialog", "Nie"))
        self.questionMakeSet_lbl.setText(_translate("Dialog", "Czy chcesz przejść do finalnego tworzenia zbioru APP oraz metadanych? (Tak - przycisk Dalej przeniesie do narzędzia tworzenia zbioru APP)"))
        self.yesMakeSet_radioBtn.setText(_translate("Dialog", "Tak"))
        self.noMakeSet_radioBtn.setText(_translate("Dialog", "Nie"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.generate_btn.setText(_translate("Dialog", "Generuj"))
        self.next_btn.setText(_translate("Dialog", "Dalej"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
