# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zbior_przygotowanie_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(672, 407)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.instruction_scrollArea = QtWidgets.QScrollArea(Dialog)
        self.instruction_scrollArea.setWidgetResizable(True)
        self.instruction_scrollArea.setObjectName("instruction_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 643, 118))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.instruction_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.instruction_lbl.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.instruction_lbl.setFont(font)
        self.instruction_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.instruction_lbl.setScaledContents(False)
        self.instruction_lbl.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.instruction_lbl.setWordWrap(True)
        self.instruction_lbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.instruction_lbl.setObjectName("instruction_lbl")
        self.gridLayout.addWidget(self.instruction_lbl, 1, 0, 1, 1)
        self.instruction_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.instruction_scrollArea)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addSet_lbl = QtWidgets.QLabel(Dialog)
        self.addSet_lbl.setObjectName("addSet_lbl")
        self.horizontalLayout.addWidget(self.addSet_lbl)
        self.addFile_widget = QgsFileWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFile_widget.sizePolicy().hasHeightForWidth())
        self.addFile_widget.setSizePolicy(sizePolicy)
        self.addFile_widget.setObjectName("addFile_widget")
        self.horizontalLayout.addWidget(self.addFile_widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addApp_lbl = QtWidgets.QLabel(Dialog)
        self.addApp_lbl.setObjectName("addApp_lbl")
        self.horizontalLayout_3.addWidget(self.addApp_lbl)
        self.addElement_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addElement_btn.setFont(font)
        self.addElement_btn.setObjectName("addElement_btn")
        self.horizontalLayout_3.addWidget(self.addElement_btn)
        self.deleteElement_btn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deleteElement_btn.setFont(font)
        self.deleteElement_btn.setObjectName("deleteElement_btn")
        self.horizontalLayout_3.addWidget(self.deleteElement_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.appTable_widget = QtWidgets.QTableWidget(Dialog)
        self.appTable_widget.setObjectName("appTable_widget")
        self.appTable_widget.setColumnCount(2)
        self.appTable_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appTable_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appTable_widget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.appTable_widget)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty2_lbl.sizePolicy().hasHeightForWidth())
        self.empty2_lbl.setSizePolicy(sizePolicy)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setEnabled(True)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_2.addWidget(self.prev_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.validateAndGenerate_btn = QtWidgets.QPushButton(Dialog)
        self.validateAndGenerate_btn.setObjectName("validateAndGenerate_btn")
        self.horizontalLayout_2.addWidget(self.validateAndGenerate_btn)
        self.next_btn = QtWidgets.QPushButton(Dialog)
        self.next_btn.setEnabled(True)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Przygotowanie zbioru APP"))
        self.instruction_lbl.setText(_translate("Dialog", "<html><head/><body><p><a name=\"_Hlk44677223\"/>Zbiór APP obejmuje zestaw danych przestrzennych dla wielu (co najmniej jednego) aktów planowania przestrzennego tego samego rodzaju, występujących w danej jednostce podziału terytorialnego np. miejscowe plany zagospodarowania przestrzennego gminy XXX. </p><p>Zbiór można stworzyć na dwa sposoby: <br/><span style=\" font-style:italic;\">1.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\"/><span style=\" font-style:italic;\">Stworzenie nowego zbioru</span><br/>Należy wgrać wszystkie utworzone pliki GML dla APP i wygenerować z nich zbiór. Zbiór może się składać z jednego APP, może się również składać z kilkuset APP. </p><p><span style=\" font-style:italic;\">2.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\"/><span style=\" font-style:italic;\">Aktualizacja istniejącego zbioru o nowe APP</span><br/>W polu <span style=\" font-style:italic;\">Dodaj istniejący zbiór APP (opcjonalne) </span>należy wgrać istniejący zbiór, który zostanie zaktualizowany. Następnie w polu <span style=\" font-style:italic;\">Dodaj wszystkie APP składające się na zbiór (co najmniej jeden APP)</span> należy wgrać wszystkie APP, które będą dołączone do już istniejącego zbioru. </p><p>Należy pamiętać, że granice APP nie mogą się pokrywać (na jednym obszarze nie mogą obowiązywać dwa akty tego samego typu). W sytuacji, kiedy granice APP będą na siebie nachodzić, niezbędna będzie poprawa geometrii obiektów znajdujących się w zbiorze. </p></body></html>"))
        self.addSet_lbl.setText(_translate("Dialog", "Dodaj dotychczasowy zbiór APP (opcjonalne)"))
        self.addApp_lbl.setText(_translate("Dialog", "Dodaj wszystkie APP składające się na zbiór (co najmniej jeden APP)"))
        self.addElement_btn.setText(_translate("Dialog", "+"))
        self.deleteElement_btn.setText(_translate("Dialog", "-"))
        item = self.appTable_widget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Plik APP (GML)"))
        item = self.appTable_widget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Data modyfikacji"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.validateAndGenerate_btn.setText(_translate("Dialog", "Waliduj/Generuj"))
        self.next_btn.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk przeniesie do narzędzia <span style=\" font-style:italic;\">Tworzenie / aktualizacja metadanych</span></p></body></html>"))
        self.next_btn.setText(_translate("Dialog", "Przejdź do metadanych"))
from qgsfilewidget import QgsFileWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
