# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/metadata/views/ui/metadane_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(654, 1128)
        font = QtGui.QFont()
        font.setKerning(True)
        Dialog.setFont(font)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.existingMetadata_lbl = QtWidgets.QLabel(Dialog)
        self.existingMetadata_lbl.setObjectName("existingMetadata_lbl")
        self.gridLayout_4.addWidget(self.existingMetadata_lbl, 0, 0, 1, 1)
        self.chooseFile_widget = QtWidgets.QPushButton(Dialog)
        self.chooseFile_widget.setObjectName("chooseFile_widget")
        self.gridLayout_4.addWidget(self.chooseFile_widget, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_lbl = QtWidgets.QLabel(Dialog)
        self.file_lbl.setObjectName("file_lbl")
        self.verticalLayout.addWidget(self.file_lbl)
        self.horizontal_line = QtWidgets.QFrame(Dialog)
        self.horizontal_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line.setObjectName("horizontal_line")
        self.verticalLayout.addWidget(self.horizontal_line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSet_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addSet_lbl.setFont(font)
        self.addSet_lbl.setObjectName("addSet_lbl")
        self.horizontalLayout_2.addWidget(self.addSet_lbl)
        self.chooseSet_widget = QgsFileWidget(Dialog)
        self.chooseSet_widget.setObjectName("chooseSet_widget")
        self.horizontalLayout_2.addWidget(self.chooseSet_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.titleForm_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleForm_lbl.setFont(font)
        self.titleForm_lbl.setObjectName("titleForm_lbl")
        self.verticalLayout.addWidget(self.titleForm_lbl)
        self.form_scrollArea = QtWidgets.QScrollArea(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_scrollArea.sizePolicy().hasHeightForWidth())
        self.form_scrollArea.setSizePolicy(sizePolicy)
        self.form_scrollArea.setWidgetResizable(True)
        self.form_scrollArea.setObjectName("form_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 632, 860))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox.sizePolicy().hasHeightForWidth())
        self.mGroupBox.setSizePolicy(sizePolicy)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.mLineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit.setProperty("qgisRelation", "")
        self.mLineEdit.setObjectName("mLineEdit")
        self.hboxlayout.addWidget(self.mLineEdit)
        self.tytul_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.tytul_tooltip.setToolTip("")
        self.tytul_tooltip.setText("")
        self.tytul_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip.setObjectName("tytul_tooltip")
        self.hboxlayout.addWidget(self.tytul_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label1 = QtWidgets.QLabel(self.mGroupBox)
        self.label1.setObjectName("label1")
        self.hboxlayout1.addWidget(self.label1)
        self.mLineEdit1 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit1.setProperty("qgisRelation", "")
        self.mLineEdit1.setObjectName("mLineEdit1")
        self.hboxlayout1.addWidget(self.mLineEdit1)
        self.streszczenie_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.streszczenie_tooltip.setToolTip("")
        self.streszczenie_tooltip.setText("")
        self.streszczenie_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.streszczenie_tooltip.setObjectName("streszczenie_tooltip")
        self.hboxlayout1.addWidget(self.streszczenie_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label2 = QtWidgets.QLabel(self.mGroupBox)
        self.label2.setObjectName("label2")
        self.hboxlayout2.addWidget(self.label2)
        self.mLineEdit2 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit2.setProperty("qgisRelation", "")
        self.mLineEdit2.setObjectName("mLineEdit2")
        self.hboxlayout2.addWidget(self.mLineEdit2)
        self.typ_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.typ_tooltip.setToolTip("")
        self.typ_tooltip.setText("")
        self.typ_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.typ_tooltip.setObjectName("typ_tooltip")
        self.hboxlayout2.addWidget(self.typ_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label3 = QtWidgets.QLabel(self.mGroupBox)
        self.label3.setObjectName("label3")
        self.hboxlayout3.addWidget(self.label3)
        self.mLineEdit3 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit3.setProperty("qgisRelation", "")
        self.mLineEdit3.setObjectName("mLineEdit3")
        self.hboxlayout3.addWidget(self.mLineEdit3)
        self.typ_tooltip1 = QtWidgets.QLabel(self.mGroupBox)
        self.typ_tooltip1.setToolTip("")
        self.typ_tooltip1.setText("")
        self.typ_tooltip1.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.typ_tooltip1.setObjectName("typ_tooltip1")
        self.hboxlayout3.addWidget(self.typ_tooltip1)
        self.verticalLayout_2.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label4 = QtWidgets.QLabel(self.mGroupBox)
        self.label4.setObjectName("label4")
        self.hboxlayout4.addWidget(self.label4)
        self.mLineEdit4 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit4.setProperty("qgisRelation", "")
        self.mLineEdit4.setObjectName("mLineEdit4")
        self.hboxlayout4.addWidget(self.mLineEdit4)
        self.typ_tooltip2 = QtWidgets.QLabel(self.mGroupBox)
        self.typ_tooltip2.setToolTip("")
        self.typ_tooltip2.setText("")
        self.typ_tooltip2.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.typ_tooltip2.setObjectName("typ_tooltip2")
        self.hboxlayout4.addWidget(self.typ_tooltip2)
        self.verticalLayout_2.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label5 = QtWidgets.QLabel(self.mGroupBox)
        self.label5.setObjectName("label5")
        self.hboxlayout5.addWidget(self.label5)
        self.mLineEdit5 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit5.setProperty("qgisRelation", "")
        self.mLineEdit5.setObjectName("mLineEdit5")
        self.hboxlayout5.addWidget(self.mLineEdit5)
        self.typ_tooltip3 = QtWidgets.QLabel(self.mGroupBox)
        self.typ_tooltip3.setToolTip("")
        self.typ_tooltip3.setText("")
        self.typ_tooltip3.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.typ_tooltip3.setObjectName("typ_tooltip3")
        self.hboxlayout5.addWidget(self.typ_tooltip3)
        self.verticalLayout_2.addLayout(self.hboxlayout5)
        self.hboxlayout6 = QtWidgets.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label6 = QtWidgets.QLabel(self.mGroupBox)
        self.label6.setObjectName("label6")
        self.hboxlayout6.addWidget(self.label6)
        self.mLineEdit6 = QgsFilterLineEdit(self.mGroupBox)
        self.mLineEdit6.setProperty("qgisRelation", "")
        self.mLineEdit6.setObjectName("mLineEdit6")
        self.hboxlayout6.addWidget(self.mLineEdit6)
        self.typ_tooltip4 = QtWidgets.QLabel(self.mGroupBox)
        self.typ_tooltip4.setToolTip("")
        self.typ_tooltip4.setText("")
        self.typ_tooltip4.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.typ_tooltip4.setObjectName("typ_tooltip4")
        self.hboxlayout6.addWidget(self.typ_tooltip4)
        self.verticalLayout_2.addLayout(self.hboxlayout6)
        self.gridLayout_2.addWidget(self.mGroupBox, 1, 0, 1, 2)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_2.sizePolicy().hasHeightForWidth())
        self.mGroupBox_2.setSizePolicy(sizePolicy)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.hboxlayout7 = QtWidgets.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label7 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label7.setObjectName("label7")
        self.hboxlayout7.addWidget(self.label7)
        self.mLineEdit7 = QgsFilterLineEdit(self.mGroupBox_2)
        self.mLineEdit7.setProperty("qgisRelation", "")
        self.mLineEdit7.setObjectName("mLineEdit7")
        self.hboxlayout7.addWidget(self.mLineEdit7)
        self.tytul_tooltip1 = QtWidgets.QLabel(self.mGroupBox_2)
        self.tytul_tooltip1.setToolTip("")
        self.tytul_tooltip1.setText("")
        self.tytul_tooltip1.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip1.setObjectName("tytul_tooltip1")
        self.hboxlayout7.addWidget(self.tytul_tooltip1)
        self.verticalLayout_21.addLayout(self.hboxlayout7)
        self.gridLayout_2.addWidget(self.mGroupBox_2, 2, 0, 1, 2)
        self.mGroupBox_3 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_3.sizePolicy().hasHeightForWidth())
        self.mGroupBox_3.setSizePolicy(sizePolicy)
        self.mGroupBox_3.setObjectName("mGroupBox_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.mGroupBox_3)
        self.verticalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.hboxlayout8 = QtWidgets.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label8 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label8.setObjectName("label8")
        self.hboxlayout8.addWidget(self.label8)
        self.mLineEdit8 = QgsFilterLineEdit(self.mGroupBox_3)
        self.mLineEdit8.setProperty("qgisRelation", "")
        self.mLineEdit8.setObjectName("mLineEdit8")
        self.hboxlayout8.addWidget(self.mLineEdit8)
        self.tytul_tooltip2 = QtWidgets.QLabel(self.mGroupBox_3)
        self.tytul_tooltip2.setToolTip("")
        self.tytul_tooltip2.setText("")
        self.tytul_tooltip2.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip2.setObjectName("tytul_tooltip2")
        self.hboxlayout8.addWidget(self.tytul_tooltip2)
        self.verticalLayout_22.addLayout(self.hboxlayout8)
        self.hboxlayout9 = QtWidgets.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.label9 = QtWidgets.QLabel(self.mGroupBox_3)
        self.label9.setObjectName("label9")
        self.hboxlayout9.addWidget(self.label9)
        self.mLineEdit9 = QgsFilterLineEdit(self.mGroupBox_3)
        self.mLineEdit9.setProperty("qgisRelation", "")
        self.mLineEdit9.setObjectName("mLineEdit9")
        self.hboxlayout9.addWidget(self.mLineEdit9)
        self.tytul_tooltip3 = QtWidgets.QLabel(self.mGroupBox_3)
        self.tytul_tooltip3.setToolTip("")
        self.tytul_tooltip3.setText("")
        self.tytul_tooltip3.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip3.setObjectName("tytul_tooltip3")
        self.hboxlayout9.addWidget(self.tytul_tooltip3)
        self.verticalLayout_22.addLayout(self.hboxlayout9)
        self.gridLayout_2.addWidget(self.mGroupBox_3, 3, 0, 1, 2)
        self.mGroupBox_4 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_4.sizePolicy().hasHeightForWidth())
        self.mGroupBox_4.setSizePolicy(sizePolicy)
        self.mGroupBox_4.setObjectName("mGroupBox_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.mGroupBox_4)
        self.verticalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.hboxlayout10 = QtWidgets.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.label10 = QtWidgets.QLabel(self.mGroupBox_4)
        self.label10.setObjectName("label10")
        self.hboxlayout10.addWidget(self.label10)
        self.mLineEdit10 = QgsFilterLineEdit(self.mGroupBox_4)
        self.mLineEdit10.setProperty("qgisRelation", "")
        self.mLineEdit10.setObjectName("mLineEdit10")
        self.hboxlayout10.addWidget(self.mLineEdit10)
        self.tytul_tooltip4 = QtWidgets.QLabel(self.mGroupBox_4)
        self.tytul_tooltip4.setToolTip("")
        self.tytul_tooltip4.setText("")
        self.tytul_tooltip4.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip4.setObjectName("tytul_tooltip4")
        self.hboxlayout10.addWidget(self.tytul_tooltip4)
        self.verticalLayout_23.addLayout(self.hboxlayout10)
        self.hboxlayout11 = QtWidgets.QHBoxLayout()
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.label11 = QtWidgets.QLabel(self.mGroupBox_4)
        self.label11.setObjectName("label11")
        self.hboxlayout11.addWidget(self.label11)
        self.mLineEdit11 = QgsFilterLineEdit(self.mGroupBox_4)
        self.mLineEdit11.setProperty("qgisRelation", "")
        self.mLineEdit11.setObjectName("mLineEdit11")
        self.hboxlayout11.addWidget(self.mLineEdit11)
        self.tytul_tooltip5 = QtWidgets.QLabel(self.mGroupBox_4)
        self.tytul_tooltip5.setToolTip("")
        self.tytul_tooltip5.setText("")
        self.tytul_tooltip5.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip5.setObjectName("tytul_tooltip5")
        self.hboxlayout11.addWidget(self.tytul_tooltip5)
        self.verticalLayout_23.addLayout(self.hboxlayout11)
        self.gridLayout_2.addWidget(self.mGroupBox_4, 4, 0, 1, 2)
        self.mGroupBox_5 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_5.setSizePolicy(sizePolicy)
        self.mGroupBox_5.setObjectName("mGroupBox_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.mGroupBox_5)
        self.verticalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.hboxlayout12 = QtWidgets.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.label12 = QtWidgets.QLabel(self.mGroupBox_5)
        self.label12.setObjectName("label12")
        self.hboxlayout12.addWidget(self.label12)
        self.mLineEdit12 = QgsFilterLineEdit(self.mGroupBox_5)
        self.mLineEdit12.setProperty("qgisRelation", "")
        self.mLineEdit12.setObjectName("mLineEdit12")
        self.hboxlayout12.addWidget(self.mLineEdit12)
        self.tytul_tooltip6 = QtWidgets.QLabel(self.mGroupBox_5)
        self.tytul_tooltip6.setToolTip("")
        self.tytul_tooltip6.setText("")
        self.tytul_tooltip6.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip6.setObjectName("tytul_tooltip6")
        self.hboxlayout12.addWidget(self.tytul_tooltip6)
        self.verticalLayout_24.addLayout(self.hboxlayout12)
        self.hboxlayout13 = QtWidgets.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.label13 = QtWidgets.QLabel(self.mGroupBox_5)
        self.label13.setObjectName("label13")
        self.hboxlayout13.addWidget(self.label13)
        self.mLineEdit13 = QgsFilterLineEdit(self.mGroupBox_5)
        self.mLineEdit13.setProperty("qgisRelation", "")
        self.mLineEdit13.setObjectName("mLineEdit13")
        self.hboxlayout13.addWidget(self.mLineEdit13)
        self.tytul_tooltip7 = QtWidgets.QLabel(self.mGroupBox_5)
        self.tytul_tooltip7.setToolTip("")
        self.tytul_tooltip7.setText("")
        self.tytul_tooltip7.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip7.setObjectName("tytul_tooltip7")
        self.hboxlayout13.addWidget(self.tytul_tooltip7)
        self.verticalLayout_24.addLayout(self.hboxlayout13)
        self.gridLayout_2.addWidget(self.mGroupBox_5, 5, 0, 1, 2)
        self.mGroupBox_6 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_6.sizePolicy().hasHeightForWidth())
        self.mGroupBox_6.setSizePolicy(sizePolicy)
        self.mGroupBox_6.setObjectName("mGroupBox_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.mGroupBox_6)
        self.verticalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.hboxlayout14 = QtWidgets.QHBoxLayout()
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.label14 = QtWidgets.QLabel(self.mGroupBox_6)
        self.label14.setObjectName("label14")
        self.hboxlayout14.addWidget(self.label14)
        self.mLineEdit14 = QgsFilterLineEdit(self.mGroupBox_6)
        self.mLineEdit14.setProperty("qgisRelation", "")
        self.mLineEdit14.setObjectName("mLineEdit14")
        self.hboxlayout14.addWidget(self.mLineEdit14)
        self.tytul_tooltip8 = QtWidgets.QLabel(self.mGroupBox_6)
        self.tytul_tooltip8.setToolTip("")
        self.tytul_tooltip8.setText("")
        self.tytul_tooltip8.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip8.setObjectName("tytul_tooltip8")
        self.hboxlayout14.addWidget(self.tytul_tooltip8)
        self.verticalLayout_25.addLayout(self.hboxlayout14)
        self.hboxlayout15 = QtWidgets.QHBoxLayout()
        self.hboxlayout15.setObjectName("hboxlayout15")
        self.label15 = QtWidgets.QLabel(self.mGroupBox_6)
        self.label15.setObjectName("label15")
        self.hboxlayout15.addWidget(self.label15)
        self.mLineEdit15 = QgsFilterLineEdit(self.mGroupBox_6)
        self.mLineEdit15.setProperty("qgisRelation", "")
        self.mLineEdit15.setObjectName("mLineEdit15")
        self.hboxlayout15.addWidget(self.mLineEdit15)
        self.tytul_tooltip9 = QtWidgets.QLabel(self.mGroupBox_6)
        self.tytul_tooltip9.setToolTip("")
        self.tytul_tooltip9.setText("")
        self.tytul_tooltip9.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip9.setObjectName("tytul_tooltip9")
        self.hboxlayout15.addWidget(self.tytul_tooltip9)
        self.verticalLayout_25.addLayout(self.hboxlayout15)
        self.hboxlayout16 = QtWidgets.QHBoxLayout()
        self.hboxlayout16.setObjectName("hboxlayout16")
        self.label16 = QtWidgets.QLabel(self.mGroupBox_6)
        self.label16.setObjectName("label16")
        self.hboxlayout16.addWidget(self.label16)
        self.mLineEdit16 = QgsFilterLineEdit(self.mGroupBox_6)
        self.mLineEdit16.setProperty("qgisRelation", "")
        self.mLineEdit16.setObjectName("mLineEdit16")
        self.hboxlayout16.addWidget(self.mLineEdit16)
        self.tytul_tooltip10 = QtWidgets.QLabel(self.mGroupBox_6)
        self.tytul_tooltip10.setToolTip("")
        self.tytul_tooltip10.setText("")
        self.tytul_tooltip10.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip10.setObjectName("tytul_tooltip10")
        self.hboxlayout16.addWidget(self.tytul_tooltip10)
        self.verticalLayout_25.addLayout(self.hboxlayout16)
        self.gridLayout_2.addWidget(self.mGroupBox_6, 6, 0, 1, 2)
        self.mGroupBox_7 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_7.sizePolicy().hasHeightForWidth())
        self.mGroupBox_7.setSizePolicy(sizePolicy)
        self.mGroupBox_7.setObjectName("mGroupBox_7")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.mGroupBox_7)
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.hboxlayout17 = QtWidgets.QHBoxLayout()
        self.hboxlayout17.setObjectName("hboxlayout17")
        self.label17 = QtWidgets.QLabel(self.mGroupBox_7)
        self.label17.setObjectName("label17")
        self.hboxlayout17.addWidget(self.label17)
        self.mLineEdit17 = QgsFilterLineEdit(self.mGroupBox_7)
        self.mLineEdit17.setProperty("qgisRelation", "")
        self.mLineEdit17.setObjectName("mLineEdit17")
        self.hboxlayout17.addWidget(self.mLineEdit17)
        self.tytul_tooltip11 = QtWidgets.QLabel(self.mGroupBox_7)
        self.tytul_tooltip11.setToolTip("")
        self.tytul_tooltip11.setText("")
        self.tytul_tooltip11.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip11.setObjectName("tytul_tooltip11")
        self.hboxlayout17.addWidget(self.tytul_tooltip11)
        self.verticalLayout_26.addLayout(self.hboxlayout17)
        self.hboxlayout18 = QtWidgets.QHBoxLayout()
        self.hboxlayout18.setObjectName("hboxlayout18")
        self.label18 = QtWidgets.QLabel(self.mGroupBox_7)
        self.label18.setObjectName("label18")
        self.hboxlayout18.addWidget(self.label18)
        self.mLineEdit18 = QgsFilterLineEdit(self.mGroupBox_7)
        self.mLineEdit18.setProperty("qgisRelation", "")
        self.mLineEdit18.setObjectName("mLineEdit18")
        self.hboxlayout18.addWidget(self.mLineEdit18)
        self.tytul_tooltip12 = QtWidgets.QLabel(self.mGroupBox_7)
        self.tytul_tooltip12.setToolTip("")
        self.tytul_tooltip12.setText("")
        self.tytul_tooltip12.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip12.setObjectName("tytul_tooltip12")
        self.hboxlayout18.addWidget(self.tytul_tooltip12)
        self.verticalLayout_26.addLayout(self.hboxlayout18)
        self.gridLayout_2.addWidget(self.mGroupBox_7, 7, 0, 1, 2)
        self.mGroupBox_8 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_8.sizePolicy().hasHeightForWidth())
        self.mGroupBox_8.setSizePolicy(sizePolicy)
        self.mGroupBox_8.setObjectName("mGroupBox_8")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mGroupBox_8)
        self.verticalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.hboxlayout19 = QtWidgets.QHBoxLayout()
        self.hboxlayout19.setObjectName("hboxlayout19")
        self.label19 = QtWidgets.QLabel(self.mGroupBox_8)
        self.label19.setObjectName("label19")
        self.hboxlayout19.addWidget(self.label19)
        self.mLineEdit19 = QgsFilterLineEdit(self.mGroupBox_8)
        self.mLineEdit19.setProperty("qgisRelation", "")
        self.mLineEdit19.setObjectName("mLineEdit19")
        self.hboxlayout19.addWidget(self.mLineEdit19)
        self.tytul_tooltip13 = QtWidgets.QLabel(self.mGroupBox_8)
        self.tytul_tooltip13.setToolTip("")
        self.tytul_tooltip13.setText("")
        self.tytul_tooltip13.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip13.setObjectName("tytul_tooltip13")
        self.hboxlayout19.addWidget(self.tytul_tooltip13)
        self.verticalLayout_27.addLayout(self.hboxlayout19)
        self.hboxlayout20 = QtWidgets.QHBoxLayout()
        self.hboxlayout20.setObjectName("hboxlayout20")
        self.label20 = QtWidgets.QLabel(self.mGroupBox_8)
        self.label20.setObjectName("label20")
        self.hboxlayout20.addWidget(self.label20)
        self.mLineEdit20 = QgsFilterLineEdit(self.mGroupBox_8)
        self.mLineEdit20.setProperty("qgisRelation", "")
        self.mLineEdit20.setObjectName("mLineEdit20")
        self.hboxlayout20.addWidget(self.mLineEdit20)
        self.tytul_tooltip14 = QtWidgets.QLabel(self.mGroupBox_8)
        self.tytul_tooltip14.setToolTip("")
        self.tytul_tooltip14.setText("")
        self.tytul_tooltip14.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip14.setObjectName("tytul_tooltip14")
        self.hboxlayout20.addWidget(self.tytul_tooltip14)
        self.verticalLayout_27.addLayout(self.hboxlayout20)
        self.gridLayout_2.addWidget(self.mGroupBox_8, 8, 0, 1, 2)
        self.mGroupBox_9 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_9.sizePolicy().hasHeightForWidth())
        self.mGroupBox_9.setSizePolicy(sizePolicy)
        self.mGroupBox_9.setObjectName("mGroupBox_9")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.mGroupBox_9)
        self.verticalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.hboxlayout21 = QtWidgets.QHBoxLayout()
        self.hboxlayout21.setObjectName("hboxlayout21")
        self.label21 = QtWidgets.QLabel(self.mGroupBox_9)
        self.label21.setObjectName("label21")
        self.hboxlayout21.addWidget(self.label21)
        self.mLineEdit21 = QgsFilterLineEdit(self.mGroupBox_9)
        self.mLineEdit21.setProperty("qgisRelation", "")
        self.mLineEdit21.setObjectName("mLineEdit21")
        self.hboxlayout21.addWidget(self.mLineEdit21)
        self.tytul_tooltip15 = QtWidgets.QLabel(self.mGroupBox_9)
        self.tytul_tooltip15.setToolTip("")
        self.tytul_tooltip15.setText("")
        self.tytul_tooltip15.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip15.setObjectName("tytul_tooltip15")
        self.hboxlayout21.addWidget(self.tytul_tooltip15)
        self.verticalLayout_28.addLayout(self.hboxlayout21)
        self.hboxlayout22 = QtWidgets.QHBoxLayout()
        self.hboxlayout22.setObjectName("hboxlayout22")
        self.label22 = QtWidgets.QLabel(self.mGroupBox_9)
        self.label22.setObjectName("label22")
        self.hboxlayout22.addWidget(self.label22)
        self.mLineEdit22 = QgsFilterLineEdit(self.mGroupBox_9)
        self.mLineEdit22.setProperty("qgisRelation", "")
        self.mLineEdit22.setObjectName("mLineEdit22")
        self.hboxlayout22.addWidget(self.mLineEdit22)
        self.tytul_tooltip16 = QtWidgets.QLabel(self.mGroupBox_9)
        self.tytul_tooltip16.setToolTip("")
        self.tytul_tooltip16.setText("")
        self.tytul_tooltip16.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip16.setObjectName("tytul_tooltip16")
        self.hboxlayout22.addWidget(self.tytul_tooltip16)
        self.verticalLayout_28.addLayout(self.hboxlayout22)
        self.gridLayout_2.addWidget(self.mGroupBox_9, 9, 0, 1, 2)
        self.mGroupBox_10 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_10.sizePolicy().hasHeightForWidth())
        self.mGroupBox_10.setSizePolicy(sizePolicy)
        self.mGroupBox_10.setObjectName("mGroupBox_10")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.mGroupBox_10)
        self.verticalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.hboxlayout23 = QtWidgets.QHBoxLayout()
        self.hboxlayout23.setObjectName("hboxlayout23")
        self.label23 = QtWidgets.QLabel(self.mGroupBox_10)
        self.label23.setObjectName("label23")
        self.hboxlayout23.addWidget(self.label23)
        self.mLineEdit23 = QgsFilterLineEdit(self.mGroupBox_10)
        self.mLineEdit23.setProperty("qgisRelation", "")
        self.mLineEdit23.setObjectName("mLineEdit23")
        self.hboxlayout23.addWidget(self.mLineEdit23)
        self.tytul_tooltip17 = QtWidgets.QLabel(self.mGroupBox_10)
        self.tytul_tooltip17.setToolTip("")
        self.tytul_tooltip17.setText("")
        self.tytul_tooltip17.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip17.setObjectName("tytul_tooltip17")
        self.hboxlayout23.addWidget(self.tytul_tooltip17)
        self.verticalLayout_29.addLayout(self.hboxlayout23)
        self.hboxlayout24 = QtWidgets.QHBoxLayout()
        self.hboxlayout24.setObjectName("hboxlayout24")
        self.label24 = QtWidgets.QLabel(self.mGroupBox_10)
        self.label24.setObjectName("label24")
        self.hboxlayout24.addWidget(self.label24)
        self.mLineEdit24 = QgsFilterLineEdit(self.mGroupBox_10)
        self.mLineEdit24.setProperty("qgisRelation", "")
        self.mLineEdit24.setObjectName("mLineEdit24")
        self.hboxlayout24.addWidget(self.mLineEdit24)
        self.tytul_tooltip18 = QtWidgets.QLabel(self.mGroupBox_10)
        self.tytul_tooltip18.setToolTip("")
        self.tytul_tooltip18.setText("")
        self.tytul_tooltip18.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip18.setObjectName("tytul_tooltip18")
        self.hboxlayout24.addWidget(self.tytul_tooltip18)
        self.verticalLayout_29.addLayout(self.hboxlayout24)
        self.gridLayout_2.addWidget(self.mGroupBox_10, 10, 0, 1, 2)
        self.mGroupBox_11 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_11.sizePolicy().hasHeightForWidth())
        self.mGroupBox_11.setSizePolicy(sizePolicy)
        self.mGroupBox_11.setObjectName("mGroupBox_11")
        self.verticalLayout_210 = QtWidgets.QVBoxLayout(self.mGroupBox_11)
        self.verticalLayout_210.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_210.setObjectName("verticalLayout_210")
        self.hboxlayout25 = QtWidgets.QHBoxLayout()
        self.hboxlayout25.setObjectName("hboxlayout25")
        self.label25 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label25.setObjectName("label25")
        self.hboxlayout25.addWidget(self.label25)
        self.mLineEdit25 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit25.setProperty("qgisRelation", "")
        self.mLineEdit25.setObjectName("mLineEdit25")
        self.hboxlayout25.addWidget(self.mLineEdit25)
        self.tytul_tooltip19 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip19.setToolTip("")
        self.tytul_tooltip19.setText("")
        self.tytul_tooltip19.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip19.setObjectName("tytul_tooltip19")
        self.hboxlayout25.addWidget(self.tytul_tooltip19)
        self.verticalLayout_210.addLayout(self.hboxlayout25)
        self.hboxlayout26 = QtWidgets.QHBoxLayout()
        self.hboxlayout26.setObjectName("hboxlayout26")
        self.label26 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label26.setObjectName("label26")
        self.hboxlayout26.addWidget(self.label26)
        self.mLineEdit26 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit26.setProperty("qgisRelation", "")
        self.mLineEdit26.setObjectName("mLineEdit26")
        self.hboxlayout26.addWidget(self.mLineEdit26)
        self.tytul_tooltip20 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip20.setToolTip("")
        self.tytul_tooltip20.setText("")
        self.tytul_tooltip20.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip20.setObjectName("tytul_tooltip20")
        self.hboxlayout26.addWidget(self.tytul_tooltip20)
        self.verticalLayout_210.addLayout(self.hboxlayout26)
        self.hboxlayout27 = QtWidgets.QHBoxLayout()
        self.hboxlayout27.setObjectName("hboxlayout27")
        self.label27 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label27.setObjectName("label27")
        self.hboxlayout27.addWidget(self.label27)
        self.mLineEdit27 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit27.setProperty("qgisRelation", "")
        self.mLineEdit27.setObjectName("mLineEdit27")
        self.hboxlayout27.addWidget(self.mLineEdit27)
        self.tytul_tooltip21 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip21.setToolTip("")
        self.tytul_tooltip21.setText("")
        self.tytul_tooltip21.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip21.setObjectName("tytul_tooltip21")
        self.hboxlayout27.addWidget(self.tytul_tooltip21)
        self.verticalLayout_210.addLayout(self.hboxlayout27)
        self.gridLayout_2.addWidget(self.mGroupBox_11, 11, 0, 1, 2)
        self.mGroupBox_12 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12.setSizePolicy(sizePolicy)
        self.mGroupBox_12.setObjectName("mGroupBox_12")
        self.verticalLayout_211 = QtWidgets.QVBoxLayout(self.mGroupBox_12)
        self.verticalLayout_211.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_211.setObjectName("verticalLayout_211")
        self.hboxlayout28 = QtWidgets.QHBoxLayout()
        self.hboxlayout28.setObjectName("hboxlayout28")
        self.label28 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label28.setObjectName("label28")
        self.hboxlayout28.addWidget(self.label28)
        self.mLineEdit28 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit28.setProperty("qgisRelation", "")
        self.mLineEdit28.setObjectName("mLineEdit28")
        self.hboxlayout28.addWidget(self.mLineEdit28)
        self.tytul_tooltip22 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip22.setToolTip("")
        self.tytul_tooltip22.setText("")
        self.tytul_tooltip22.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip22.setObjectName("tytul_tooltip22")
        self.hboxlayout28.addWidget(self.tytul_tooltip22)
        self.verticalLayout_211.addLayout(self.hboxlayout28)
        self.hboxlayout29 = QtWidgets.QHBoxLayout()
        self.hboxlayout29.setObjectName("hboxlayout29")
        self.label29 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label29.setObjectName("label29")
        self.hboxlayout29.addWidget(self.label29)
        self.mLineEdit29 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit29.setProperty("qgisRelation", "")
        self.mLineEdit29.setObjectName("mLineEdit29")
        self.hboxlayout29.addWidget(self.mLineEdit29)
        self.tytul_tooltip23 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip23.setToolTip("")
        self.tytul_tooltip23.setText("")
        self.tytul_tooltip23.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip23.setObjectName("tytul_tooltip23")
        self.hboxlayout29.addWidget(self.tytul_tooltip23)
        self.verticalLayout_211.addLayout(self.hboxlayout29)
        self.hboxlayout30 = QtWidgets.QHBoxLayout()
        self.hboxlayout30.setObjectName("hboxlayout30")
        self.label30 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label30.setObjectName("label30")
        self.hboxlayout30.addWidget(self.label30)
        self.mLineEdit30 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit30.setProperty("qgisRelation", "")
        self.mLineEdit30.setObjectName("mLineEdit30")
        self.hboxlayout30.addWidget(self.mLineEdit30)
        self.tytul_tooltip24 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip24.setToolTip("")
        self.tytul_tooltip24.setText("")
        self.tytul_tooltip24.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip24.setObjectName("tytul_tooltip24")
        self.hboxlayout30.addWidget(self.tytul_tooltip24)
        self.verticalLayout_211.addLayout(self.hboxlayout30)
        self.hboxlayout31 = QtWidgets.QHBoxLayout()
        self.hboxlayout31.setObjectName("hboxlayout31")
        self.label31 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label31.setObjectName("label31")
        self.hboxlayout31.addWidget(self.label31)
        self.mLineEdit31 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit31.setProperty("qgisRelation", "")
        self.mLineEdit31.setObjectName("mLineEdit31")
        self.hboxlayout31.addWidget(self.mLineEdit31)
        self.tytul_tooltip25 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip25.setToolTip("")
        self.tytul_tooltip25.setText("")
        self.tytul_tooltip25.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip25.setObjectName("tytul_tooltip25")
        self.hboxlayout31.addWidget(self.tytul_tooltip25)
        self.verticalLayout_211.addLayout(self.hboxlayout31)
        self.mGroupBox_12_5 = QgsCollapsibleGroupBox(self.mGroupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12_5.setSizePolicy(sizePolicy)
        self.mGroupBox_12_5.setObjectName("mGroupBox_12_5")
        self.verticalLayout_212 = QtWidgets.QVBoxLayout(self.mGroupBox_12_5)
        self.verticalLayout_212.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_212.setObjectName("verticalLayout_212")
        self.hboxlayout32 = QtWidgets.QHBoxLayout()
        self.hboxlayout32.setObjectName("hboxlayout32")
        self.label32 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.label32.setObjectName("label32")
        self.hboxlayout32.addWidget(self.label32)
        self.mLineEdit32 = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.mLineEdit32.setProperty("qgisRelation", "")
        self.mLineEdit32.setObjectName("mLineEdit32")
        self.hboxlayout32.addWidget(self.mLineEdit32)
        self.tytul_tooltip26 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.tytul_tooltip26.setToolTip("")
        self.tytul_tooltip26.setText("")
        self.tytul_tooltip26.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip26.setObjectName("tytul_tooltip26")
        self.hboxlayout32.addWidget(self.tytul_tooltip26)
        self.verticalLayout_212.addLayout(self.hboxlayout32)
        self.hboxlayout33 = QtWidgets.QHBoxLayout()
        self.hboxlayout33.setObjectName("hboxlayout33")
        self.label33 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.label33.setObjectName("label33")
        self.hboxlayout33.addWidget(self.label33)
        self.mLineEdit33 = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.mLineEdit33.setProperty("qgisRelation", "")
        self.mLineEdit33.setObjectName("mLineEdit33")
        self.hboxlayout33.addWidget(self.mLineEdit33)
        self.tytul_tooltip27 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.tytul_tooltip27.setToolTip("")
        self.tytul_tooltip27.setText("")
        self.tytul_tooltip27.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip27.setObjectName("tytul_tooltip27")
        self.hboxlayout33.addWidget(self.tytul_tooltip27)
        self.verticalLayout_212.addLayout(self.hboxlayout33)
        self.verticalLayout_211.addWidget(self.mGroupBox_12_5)
        self.gridLayout_2.addWidget(self.mGroupBox_12, 12, 0, 1, 2)
        self.form_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.form_scrollArea)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.send_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send_lbl.setFont(font)
        self.send_lbl.setObjectName("send_lbl")
        self.verticalLayout.addWidget(self.send_lbl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.server_btn = QtWidgets.QPushButton(Dialog)
        self.server_btn.setEnabled(False)
        self.server_btn.setObjectName("server_btn")
        self.gridLayout.addWidget(self.server_btn, 0, 1, 1, 1)
        self.email_btn = QtWidgets.QPushButton(Dialog)
        self.email_btn.setEnabled(False)
        self.email_btn.setObjectName("email_btn")
        self.gridLayout.addWidget(self.email_btn, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_3.addWidget(self.prev_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.validateAndSave_btn = QtWidgets.QPushButton(Dialog)
        self.validateAndSave_btn.setObjectName("validateAndSave_btn")
        self.horizontalLayout_3.addWidget(self.validateAndSave_btn)
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setEnabled(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Metadane"))
        self.existingMetadata_lbl.setText(_translate("Dialog", "Aktualizuj plik z metadanymi (opcjonalne)    "))
        self.chooseFile_widget.setText(_translate("Dialog", "..."))
        self.file_lbl.setText(_translate("Dialog", "..."))
        self.addSet_lbl.setText(_translate("Dialog", "Wybierz plik GML dla zbioru APP (opcjonalne)"))
        self.titleForm_lbl.setText(_translate("Dialog", "Formularz metadanych:"))
        self.mGroupBox.setTitle(_translate("Dialog", "Identyfikacja*"))
        self.label.setText(_translate("Dialog", "Tytuł zbioru*"))
        self.label1.setText(_translate("Dialog", "Streszczenie*"))
        self.label2.setText(_translate("Dialog", "Typ zbioru*"))
        self.label3.setText(_translate("Dialog", "Adres zbioru"))
        self.label4.setText(_translate("Dialog", "Unikalny identyfikator zbioru*"))
        self.label5.setText(_translate("Dialog", "Język zbioru*"))
        self.label6.setText(_translate("Dialog", "Kodowanie znaków"))
        self.mGroupBox_2.setTitle(_translate("Dialog", "Klasyfikacja danych przestrzennych*"))
        self.label7.setText(_translate("Dialog", "Kategoria tematyczna*"))
        self.mGroupBox_3.setTitle(_translate("Dialog", "Słowo kluczowe"))
        self.label8.setText(_translate("Dialog", "Wartość słowa kluczowego*"))
        self.label9.setText(_translate("Dialog", "Standardowy słownik źródłowy"))
        self.mGroupBox_4.setTitle(_translate("Dialog", "Położenie geograficzne"))
        self.label10.setText(_translate("Dialog", "Geograficzny prostokąt ograniczojący"))
        self.label11.setText(_translate("Dialog", "System odniesienia za pomocą współrzędnych"))
        self.mGroupBox_5.setTitle(_translate("Dialog", "Odniesienie czasowe"))
        self.label12.setText(_translate("Dialog", "Data utworzenia"))
        self.label13.setText(_translate("Dialog", "Data opublikowania"))
        self.mGroupBox_6.setTitle(_translate("Dialog", "Jakość i ważność"))
        self.label14.setText(_translate("Dialog", "Pochodzenie"))
        self.label15.setText(_translate("Dialog", "Rozdzielczość przestrzenna"))
        self.label16.setText(_translate("Dialog", "Typ reprezentacji przestrzennej"))
        self.mGroupBox_7.setTitle(_translate("Dialog", "Zgodność"))
        self.label17.setText(_translate("Dialog", "Specyfikacja"))
        self.label18.setText(_translate("Dialog", "Stopień"))
        self.mGroupBox_8.setTitle(_translate("Dialog", "Wymogi dotyczące dostępu i użytkowania"))
        self.label19.setText(_translate("Dialog", "Warunki dotyczące dostępu i użytkowania"))
        self.label20.setText(_translate("Dialog", "Ograniczenia w publicznym dostępie"))
        self.mGroupBox_9.setTitle(_translate("Dialog", "Organizacje odpowiedzialne"))
        self.label21.setText(_translate("Dialog", "Jednostka odpowiedzialna"))
        self.label22.setText(_translate("Dialog", "Rola jednostki odpowiedzialnej"))
        self.mGroupBox_10.setTitle(_translate("Dialog", "Kodowanie"))
        self.label23.setText(_translate("Dialog", "Nazwa formatu"))
        self.label24.setText(_translate("Dialog", "Wersja formatu"))
        self.mGroupBox_11.setTitle(_translate("Dialog", "Informacje o utrzymaniu zbioru"))
        self.label25.setText(_translate("Dialog", "Częstotliwość aktualizacji"))
        self.label26.setText(_translate("Dialog", "Informacja o szczegółowych wymaganiach dotyczących utrzymania"))
        self.label27.setText(_translate("Dialog", "Zakres danych"))
        self.mGroupBox_12.setTitle(_translate("Dialog", "Metadane na temat metadanych"))
        self.label28.setText(_translate("Dialog", "Punkt kontaktowy metadanych"))
        self.label29.setText(_translate("Dialog", "Data metadanych"))
        self.label30.setText(_translate("Dialog", "Język metadanych"))
        self.label31.setText(_translate("Dialog", "Unikalny identyfikator rekordu (pliku) metadanych"))
        self.mGroupBox_12_5.setTitle(_translate("Dialog", "Standard metadanych"))
        self.label32.setText(_translate("Dialog", "Nazwa standardu metadanych"))
        self.label33.setText(_translate("Dialog", "Wersja standardu metadanych"))
        self.send_lbl.setText(_translate("Dialog", "Wybierz, gdzie chcesz wysłać plik z metadanymi (opcjonalne):"))
        self.server_btn.setText(_translate("Dialog", "Wyślij na serwer katalogowy"))
        self.email_btn.setText(_translate("Dialog", "Wyślij na adres email"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.validateAndSave_btn.setText(_translate("Dialog", "Waliduj/zapisz"))
        self.close_btn.setText(_translate("Dialog", "Zakończ"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsfilewidget import QgsFileWidget
from qgsfilterlineedit import QgsFilterLineEdit
