# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/metadata/views/ui/metadane_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(541, 642)
        font = QtGui.QFont()
        font.setKerning(True)
        Dialog.setFont(font)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.existingMetadata_lbl = QtWidgets.QLabel(Dialog)
        self.existingMetadata_lbl.setObjectName("existingMetadata_lbl")
        self.gridLayout_4.addWidget(self.existingMetadata_lbl, 0, 0, 1, 1)
        self.chooseFile_widget = QtWidgets.QPushButton(Dialog)
        self.chooseFile_widget.setObjectName("chooseFile_widget")
        self.gridLayout_4.addWidget(self.chooseFile_widget, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_lbl = QtWidgets.QLabel(Dialog)
        self.file_lbl.setObjectName("file_lbl")
        self.verticalLayout.addWidget(self.file_lbl)
        self.horizontal_line = QtWidgets.QFrame(Dialog)
        self.horizontal_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line.setObjectName("horizontal_line")
        self.verticalLayout.addWidget(self.horizontal_line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSet_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addSet_lbl.setFont(font)
        self.addSet_lbl.setObjectName("addSet_lbl")
        self.horizontalLayout_2.addWidget(self.addSet_lbl)
        self.chooseSet_widget = QgsFileWidget(Dialog)
        self.chooseSet_widget.setObjectName("chooseSet_widget")
        self.horizontalLayout_2.addWidget(self.chooseSet_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.titleForm_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleForm_lbl.setFont(font)
        self.titleForm_lbl.setObjectName("titleForm_lbl")
        self.verticalLayout.addWidget(self.titleForm_lbl)
        self.form_scrollArea = QtWidgets.QScrollArea(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_scrollArea.sizePolicy().hasHeightForWidth())
        self.form_scrollArea.setSizePolicy(sizePolicy)
        self.form_scrollArea.setWidgetResizable(True)
        self.form_scrollArea.setObjectName("form_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -1090, 502, 1913))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox.sizePolicy().hasHeightForWidth())
        self.mGroupBox.setSizePolicy(sizePolicy)
        self.mGroupBox.setCheckable(False)
        self.mGroupBox.setCollapsed(False)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.e1_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e1_lbl.setObjectName("e1_lbl")
        self.hboxlayout.addWidget(self.e1_lbl)
        self.e1_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e1_lineEdit.setProperty("qgisRelation", "")
        self.e1_lineEdit.setObjectName("e1_lineEdit")
        self.hboxlayout.addWidget(self.e1_lineEdit)
        self.e1_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e1_tooltip.setText("")
        self.e1_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e1_tooltip.setObjectName("e1_tooltip")
        self.hboxlayout.addWidget(self.e1_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.e2_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e2_lbl.setObjectName("e2_lbl")
        self.hboxlayout1.addWidget(self.e2_lbl)
        self.e2_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e2_lineEdit.setProperty("qgisRelation", "")
        self.e2_lineEdit.setObjectName("e2_lineEdit")
        self.hboxlayout1.addWidget(self.e2_lineEdit)
        self.e2_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e2_tooltip.setText("")
        self.e2_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e2_tooltip.setObjectName("e2_tooltip")
        self.hboxlayout1.addWidget(self.e2_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.e3_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e3_lbl.setObjectName("e3_lbl")
        self.hboxlayout2.addWidget(self.e3_lbl)
        self.e3_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e3_lineEdit.setProperty("qgisRelation", "")
        self.e3_lineEdit.setObjectName("e3_lineEdit")
        self.hboxlayout2.addWidget(self.e3_lineEdit)
        self.e3_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e3_tooltip.setText("")
        self.e3_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e3_tooltip.setObjectName("e3_tooltip")
        self.hboxlayout2.addWidget(self.e3_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.e4_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e4_lbl.setObjectName("e4_lbl")
        self.hboxlayout3.addWidget(self.e4_lbl)
        self.e4_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e4_lineEdit.setProperty("qgisRelation", "")
        self.e4_lineEdit.setObjectName("e4_lineEdit")
        self.hboxlayout3.addWidget(self.e4_lineEdit)
        self.e4_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e4_tooltip.setText("")
        self.e4_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e4_tooltip.setObjectName("e4_tooltip")
        self.hboxlayout3.addWidget(self.e4_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.e5_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e5_lbl.setObjectName("e5_lbl")
        self.hboxlayout4.addWidget(self.e5_lbl)
        self.e5_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e5_lineEdit.setProperty("qgisRelation", "")
        self.e5_lineEdit.setObjectName("e5_lineEdit")
        self.hboxlayout4.addWidget(self.e5_lineEdit)
        self.e5_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e5_tooltip.setText("")
        self.e5_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e5_tooltip.setObjectName("e5_tooltip")
        self.hboxlayout4.addWidget(self.e5_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.e6_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e6_lbl.setObjectName("e6_lbl")
        self.hboxlayout5.addWidget(self.e6_lbl)
        self.e6_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e6_lineEdit.setProperty("qgisRelation", "")
        self.e6_lineEdit.setObjectName("e6_lineEdit")
        self.hboxlayout5.addWidget(self.e6_lineEdit)
        self.e6_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e6_tooltip.setText("")
        self.e6_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e6_tooltip.setObjectName("e6_tooltip")
        self.hboxlayout5.addWidget(self.e6_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout5)
        self.hboxlayout6 = QtWidgets.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.e7_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e7_lbl.setObjectName("e7_lbl")
        self.hboxlayout6.addWidget(self.e7_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem1)
        self.e7_cmbbx = QtWidgets.QComboBox(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e7_cmbbx.sizePolicy().hasHeightForWidth())
        self.e7_cmbbx.setSizePolicy(sizePolicy)
        self.e7_cmbbx.setObjectName("e7_cmbbx")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.setItemText(0, "")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.hboxlayout6.addWidget(self.e7_cmbbx)
        self.e7_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e7_tooltip.setText("")
        self.e7_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e7_tooltip.setObjectName("e7_tooltip")
        self.hboxlayout6.addWidget(self.e7_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout6)
        self.gridLayout_2.addWidget(self.mGroupBox, 1, 0, 1, 2)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_2.sizePolicy().hasHeightForWidth())
        self.mGroupBox_2.setSizePolicy(sizePolicy)
        self.mGroupBox_2.setCollapsed(False)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.hboxlayout7 = QtWidgets.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.e8_lbl = QtWidgets.QLabel(self.mGroupBox_2)
        self.e8_lbl.setObjectName("e8_lbl")
        self.hboxlayout7.addWidget(self.e8_lbl)
        self.e8_lineEdit = QgsFilterLineEdit(self.mGroupBox_2)
        self.e8_lineEdit.setEnabled(False)
        self.e8_lineEdit.setProperty("qgisRelation", "")
        self.e8_lineEdit.setObjectName("e8_lineEdit")
        self.hboxlayout7.addWidget(self.e8_lineEdit)
        self.e8_tooltip = QtWidgets.QLabel(self.mGroupBox_2)
        self.e8_tooltip.setText("")
        self.e8_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e8_tooltip.setObjectName("e8_tooltip")
        self.hboxlayout7.addWidget(self.e8_tooltip)
        self.verticalLayout_21.addLayout(self.hboxlayout7)
        self.gridLayout_2.addWidget(self.mGroupBox_2, 2, 0, 1, 2)
        self.qgsCollapsibleGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qgsCollapsibleGroupBox.sizePolicy().hasHeightForWidth())
        self.qgsCollapsibleGroupBox.setSizePolicy(sizePolicy)
        self.qgsCollapsibleGroupBox.setCollapsed(False)
        self.qgsCollapsibleGroupBox.setObjectName("qgsCollapsibleGroupBox")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.qgsCollapsibleGroupBox)
        self.verticalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.qgsCollapsibleGroupBox)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hboxlayout8 = QtWidgets.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.e9_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.e9_lbl.setObjectName("e9_lbl")
        self.hboxlayout8.addWidget(self.e9_lbl)
        self.e9_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.e9_lineEdit.setProperty("qgisRelation", "")
        self.e9_lineEdit.setObjectName("e9_lineEdit")
        self.hboxlayout8.addWidget(self.e9_lineEdit)
        self.e9_tooltip = QtWidgets.QLabel(self.verticalGroupBox)
        self.e9_tooltip.setText("")
        self.e9_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e9_tooltip.setObjectName("e9_tooltip")
        self.hboxlayout8.addWidget(self.e9_tooltip)
        self.verticalLayout_3.addLayout(self.hboxlayout8)
        self.hboxlayout9 = QtWidgets.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.e9_add_btn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.e9_add_btn.setObjectName("e9_add_btn")
        self.hboxlayout9.addWidget(self.e9_add_btn)
        self.e9_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.e9_remove_btn.setObjectName("e9_remove_btn")
        self.hboxlayout9.addWidget(self.e9_remove_btn)
        self.verticalLayout_3.addLayout(self.hboxlayout9)
        self.e9_listWidget = QtWidgets.QListWidget(self.verticalGroupBox)
        self.e9_listWidget.setObjectName("e9_listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.e9_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.e9_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.e9_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.e9_listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.e9_listWidget)
        self.verticalLayout_22.addWidget(self.verticalGroupBox)
        self.hboxlayout10 = QtWidgets.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.e10_lbl = QtWidgets.QLabel(self.qgsCollapsibleGroupBox)
        self.e10_lbl.setObjectName("e10_lbl")
        self.hboxlayout10.addWidget(self.e10_lbl)
        self.e10_lineEdit = QgsFilterLineEdit(self.qgsCollapsibleGroupBox)
        self.e10_lineEdit.setProperty("qgisRelation", "")
        self.e10_lineEdit.setObjectName("e10_lineEdit")
        self.hboxlayout10.addWidget(self.e10_lineEdit)
        self.e10_tooltip = QtWidgets.QLabel(self.qgsCollapsibleGroupBox)
        self.e10_tooltip.setToolTip("")
        self.e10_tooltip.setText("")
        self.e10_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e10_tooltip.setObjectName("e10_tooltip")
        self.hboxlayout10.addWidget(self.e10_tooltip)
        self.verticalLayout_22.addLayout(self.hboxlayout10)
        self.gridLayout_2.addWidget(self.qgsCollapsibleGroupBox, 3, 0, 1, 2)
        self.mGroupBox_4 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_4.sizePolicy().hasHeightForWidth())
        self.mGroupBox_4.setSizePolicy(sizePolicy)
        self.mGroupBox_4.setObjectName("mGroupBox_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.mGroupBox_4)
        self.verticalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.hboxlayout11 = QtWidgets.QHBoxLayout()
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.e11_lbl = QtWidgets.QLabel(self.verticalGroupBox1)
        self.e11_lbl.setObjectName("e11_lbl")
        self.hboxlayout11.addWidget(self.e11_lbl)
        self.e11_lineEdit = QgsFilterLineEdit(self.verticalGroupBox1)
        self.e11_lineEdit.setProperty("qgisRelation", "")
        self.e11_lineEdit.setObjectName("e11_lineEdit")
        self.hboxlayout11.addWidget(self.e11_lineEdit)
        self.e11_tooltip = QtWidgets.QLabel(self.verticalGroupBox1)
        self.e11_tooltip.setText("")
        self.e11_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e11_tooltip.setObjectName("e11_tooltip")
        self.hboxlayout11.addWidget(self.e11_tooltip)
        self.verticalLayout_31.addLayout(self.hboxlayout11)
        self.hboxlayout12 = QtWidgets.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.e11_add_btn = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.e11_add_btn.setObjectName("e11_add_btn")
        self.hboxlayout12.addWidget(self.e11_add_btn)
        self.e11_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.e11_remove_btn.setObjectName("e11_remove_btn")
        self.hboxlayout12.addWidget(self.e11_remove_btn)
        self.verticalLayout_31.addLayout(self.hboxlayout12)
        self.e11_listWidget = QtWidgets.QListWidget(self.verticalGroupBox1)
        self.e11_listWidget.setObjectName("e11_listWidget")
        self.verticalLayout_31.addWidget(self.e11_listWidget)
        self.verticalLayout_23.addWidget(self.verticalGroupBox1)
        self.verticalGroupBox2 = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.hboxlayout13 = QtWidgets.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.e12_lbl = QtWidgets.QLabel(self.verticalGroupBox2)
        self.e12_lbl.setObjectName("e12_lbl")
        self.hboxlayout13.addWidget(self.e12_lbl)
        self.e12_lineEdit = QgsFilterLineEdit(self.verticalGroupBox2)
        self.e12_lineEdit.setProperty("qgisRelation", "")
        self.e12_lineEdit.setObjectName("e12_lineEdit")
        self.hboxlayout13.addWidget(self.e12_lineEdit)
        self.e12_tooltip = QtWidgets.QLabel(self.verticalGroupBox2)
        self.e12_tooltip.setText("")
        self.e12_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e12_tooltip.setObjectName("e12_tooltip")
        self.hboxlayout13.addWidget(self.e12_tooltip)
        self.verticalLayout_32.addLayout(self.hboxlayout13)
        self.hboxlayout14 = QtWidgets.QHBoxLayout()
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.e12_add_btn = QtWidgets.QPushButton(self.verticalGroupBox2)
        self.e12_add_btn.setObjectName("e12_add_btn")
        self.hboxlayout14.addWidget(self.e12_add_btn)
        self.e12_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox2)
        self.e12_remove_btn.setObjectName("e12_remove_btn")
        self.hboxlayout14.addWidget(self.e12_remove_btn)
        self.verticalLayout_32.addLayout(self.hboxlayout14)
        self.e12_listWidget = QtWidgets.QListWidget(self.verticalGroupBox2)
        self.e12_listWidget.setObjectName("e12_listWidget")
        self.verticalLayout_32.addWidget(self.e12_listWidget)
        self.verticalLayout_23.addWidget(self.verticalGroupBox2)
        self.gridLayout_2.addWidget(self.mGroupBox_4, 4, 0, 1, 2)
        self.mGroupBox_5 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_5.setSizePolicy(sizePolicy)
        self.mGroupBox_5.setObjectName("mGroupBox_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.mGroupBox_5)
        self.verticalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.hboxlayout15 = QtWidgets.QHBoxLayout()
        self.hboxlayout15.setObjectName("hboxlayout15")
        self.e13_lbl = QtWidgets.QLabel(self.mGroupBox_5)
        self.e13_lbl.setObjectName("e13_lbl")
        self.hboxlayout15.addWidget(self.e13_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout15.addItem(spacerItem2)
        self.e13_dateTimeEdit = QgsDateTimeEdit(self.mGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e13_dateTimeEdit.sizePolicy().hasHeightForWidth())
        self.e13_dateTimeEdit.setSizePolicy(sizePolicy)
        self.e13_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e13_dateTimeEdit.setObjectName("e13_dateTimeEdit")
        self.hboxlayout15.addWidget(self.e13_dateTimeEdit)
        self.e13_cmbbx = QtWidgets.QComboBox(self.mGroupBox_5)
        self.e13_cmbbx.setObjectName("e13_cmbbx")
        self.e13_cmbbx.addItem("")
        self.e13_cmbbx.addItem("")
        self.e13_cmbbx.addItem("")
        self.hboxlayout15.addWidget(self.e13_cmbbx)
        self.e13_tooltip = QtWidgets.QLabel(self.mGroupBox_5)
        self.e13_tooltip.setText("")
        self.e13_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e13_tooltip.setObjectName("e13_tooltip")
        self.hboxlayout15.addWidget(self.e13_tooltip)
        self.verticalLayout_24.addLayout(self.hboxlayout15)
        self.hboxlayout16 = QtWidgets.QHBoxLayout()
        self.hboxlayout16.setObjectName("hboxlayout16")
        self.e14_lbl = QtWidgets.QLabel(self.mGroupBox_5)
        self.e14_lbl.setObjectName("e14_lbl")
        self.hboxlayout16.addWidget(self.e14_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout16.addItem(spacerItem3)
        self.mDateTimeEdit = QgsDateTimeEdit(self.mGroupBox_5)
        self.mDateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.mDateTimeEdit.setObjectName("mDateTimeEdit")
        self.hboxlayout16.addWidget(self.mDateTimeEdit)
        self.e14_cmbbx = QtWidgets.QComboBox(self.mGroupBox_5)
        self.e14_cmbbx.setObjectName("e14_cmbbx")
        self.e14_cmbbx.addItem("")
        self.e14_cmbbx.addItem("")
        self.e14_cmbbx.addItem("")
        self.hboxlayout16.addWidget(self.e14_cmbbx)
        self.e14_tooltip = QtWidgets.QLabel(self.mGroupBox_5)
        self.e14_tooltip.setText("")
        self.e14_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e14_tooltip.setObjectName("e14_tooltip")
        self.hboxlayout16.addWidget(self.e14_tooltip)
        self.verticalLayout_24.addLayout(self.hboxlayout16)
        self.gridLayout_2.addWidget(self.mGroupBox_5, 5, 0, 1, 2)
        self.mGroupBox_6 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_6.sizePolicy().hasHeightForWidth())
        self.mGroupBox_6.setSizePolicy(sizePolicy)
        self.mGroupBox_6.setObjectName("mGroupBox_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.mGroupBox_6)
        self.verticalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.hboxlayout17 = QtWidgets.QHBoxLayout()
        self.hboxlayout17.setObjectName("hboxlayout17")
        self.e15_lbl = QtWidgets.QLabel(self.mGroupBox_6)
        self.e15_lbl.setObjectName("e15_lbl")
        self.hboxlayout17.addWidget(self.e15_lbl)
        self.e15_lineEdit = QgsFilterLineEdit(self.mGroupBox_6)
        self.e15_lineEdit.setProperty("qgisRelation", "")
        self.e15_lineEdit.setObjectName("e15_lineEdit")
        self.hboxlayout17.addWidget(self.e15_lineEdit)
        self.e15_tooltip = QtWidgets.QLabel(self.mGroupBox_6)
        self.e15_tooltip.setText("")
        self.e15_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e15_tooltip.setObjectName("e15_tooltip")
        self.hboxlayout17.addWidget(self.e15_tooltip)
        self.verticalLayout_25.addLayout(self.hboxlayout17)
        self.verticalGroupBox3 = QtWidgets.QGroupBox(self.mGroupBox_6)
        self.verticalGroupBox3.setObjectName("verticalGroupBox3")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.verticalGroupBox3)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.hboxlayout18 = QtWidgets.QHBoxLayout()
        self.hboxlayout18.setObjectName("hboxlayout18")
        self.e16_lbl = QtWidgets.QLabel(self.verticalGroupBox3)
        self.e16_lbl.setObjectName("e16_lbl")
        self.hboxlayout18.addWidget(self.e16_lbl)
        self.e16_lineEdit = QgsFilterLineEdit(self.verticalGroupBox3)
        self.e16_lineEdit.setProperty("qgisRelation", "")
        self.e16_lineEdit.setObjectName("e16_lineEdit")
        self.hboxlayout18.addWidget(self.e16_lineEdit)
        self.e16_tooltip = QtWidgets.QLabel(self.verticalGroupBox3)
        self.e16_tooltip.setText("")
        self.e16_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e16_tooltip.setObjectName("e16_tooltip")
        self.hboxlayout18.addWidget(self.e16_tooltip)
        self.verticalLayout_33.addLayout(self.hboxlayout18)
        self.hboxlayout19 = QtWidgets.QHBoxLayout()
        self.hboxlayout19.setObjectName("hboxlayout19")
        self.e12_add_btn1 = QtWidgets.QPushButton(self.verticalGroupBox3)
        self.e12_add_btn1.setObjectName("e12_add_btn1")
        self.hboxlayout19.addWidget(self.e12_add_btn1)
        self.e12_remove_btn1 = QtWidgets.QPushButton(self.verticalGroupBox3)
        self.e12_remove_btn1.setObjectName("e12_remove_btn1")
        self.hboxlayout19.addWidget(self.e12_remove_btn1)
        self.verticalLayout_33.addLayout(self.hboxlayout19)
        self.e12_listWidget1 = QtWidgets.QListWidget(self.verticalGroupBox3)
        self.e12_listWidget1.setObjectName("e12_listWidget1")
        self.verticalLayout_33.addWidget(self.e12_listWidget1)
        self.verticalLayout_25.addWidget(self.verticalGroupBox3)
        self.hboxlayout20 = QtWidgets.QHBoxLayout()
        self.hboxlayout20.setObjectName("hboxlayout20")
        self.e17_lbl = QtWidgets.QLabel(self.mGroupBox_6)
        self.e17_lbl.setObjectName("e17_lbl")
        self.hboxlayout20.addWidget(self.e17_lbl)
        self.e17_lineEdit = QgsFilterLineEdit(self.mGroupBox_6)
        self.e17_lineEdit.setEnabled(False)
        self.e17_lineEdit.setProperty("qgisRelation", "")
        self.e17_lineEdit.setObjectName("e17_lineEdit")
        self.hboxlayout20.addWidget(self.e17_lineEdit)
        self.e17_tooltip = QtWidgets.QLabel(self.mGroupBox_6)
        self.e17_tooltip.setText("")
        self.e17_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.e17_tooltip.setObjectName("e17_tooltip")
        self.hboxlayout20.addWidget(self.e17_tooltip)
        self.verticalLayout_25.addLayout(self.hboxlayout20)
        self.gridLayout_2.addWidget(self.mGroupBox_6, 6, 0, 1, 2)
        self.mGroupBox_7 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_7.sizePolicy().hasHeightForWidth())
        self.mGroupBox_7.setSizePolicy(sizePolicy)
        self.mGroupBox_7.setObjectName("mGroupBox_7")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.mGroupBox_7)
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.hboxlayout21 = QtWidgets.QHBoxLayout()
        self.hboxlayout21.setObjectName("hboxlayout21")
        self.label = QtWidgets.QLabel(self.mGroupBox_7)
        self.label.setObjectName("label")
        self.hboxlayout21.addWidget(self.label)
        self.mLineEdit = QgsFilterLineEdit(self.mGroupBox_7)
        self.mLineEdit.setProperty("qgisRelation", "")
        self.mLineEdit.setObjectName("mLineEdit")
        self.hboxlayout21.addWidget(self.mLineEdit)
        self.tytul_tooltip = QtWidgets.QLabel(self.mGroupBox_7)
        self.tytul_tooltip.setToolTip("")
        self.tytul_tooltip.setText("")
        self.tytul_tooltip.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip.setObjectName("tytul_tooltip")
        self.hboxlayout21.addWidget(self.tytul_tooltip)
        self.verticalLayout_26.addLayout(self.hboxlayout21)
        self.hboxlayout22 = QtWidgets.QHBoxLayout()
        self.hboxlayout22.setObjectName("hboxlayout22")
        self.label1 = QtWidgets.QLabel(self.mGroupBox_7)
        self.label1.setObjectName("label1")
        self.hboxlayout22.addWidget(self.label1)
        self.mLineEdit1 = QgsFilterLineEdit(self.mGroupBox_7)
        self.mLineEdit1.setProperty("qgisRelation", "")
        self.mLineEdit1.setObjectName("mLineEdit1")
        self.hboxlayout22.addWidget(self.mLineEdit1)
        self.tytul_tooltip1 = QtWidgets.QLabel(self.mGroupBox_7)
        self.tytul_tooltip1.setToolTip("")
        self.tytul_tooltip1.setText("")
        self.tytul_tooltip1.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip1.setObjectName("tytul_tooltip1")
        self.hboxlayout22.addWidget(self.tytul_tooltip1)
        self.verticalLayout_26.addLayout(self.hboxlayout22)
        self.gridLayout_2.addWidget(self.mGroupBox_7, 7, 0, 1, 2)
        self.mGroupBox_8 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_8.sizePolicy().hasHeightForWidth())
        self.mGroupBox_8.setSizePolicy(sizePolicy)
        self.mGroupBox_8.setObjectName("mGroupBox_8")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mGroupBox_8)
        self.verticalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.hboxlayout23 = QtWidgets.QHBoxLayout()
        self.hboxlayout23.setObjectName("hboxlayout23")
        self.label2 = QtWidgets.QLabel(self.mGroupBox_8)
        self.label2.setObjectName("label2")
        self.hboxlayout23.addWidget(self.label2)
        self.mLineEdit2 = QgsFilterLineEdit(self.mGroupBox_8)
        self.mLineEdit2.setProperty("qgisRelation", "")
        self.mLineEdit2.setObjectName("mLineEdit2")
        self.hboxlayout23.addWidget(self.mLineEdit2)
        self.tytul_tooltip2 = QtWidgets.QLabel(self.mGroupBox_8)
        self.tytul_tooltip2.setToolTip("")
        self.tytul_tooltip2.setText("")
        self.tytul_tooltip2.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip2.setObjectName("tytul_tooltip2")
        self.hboxlayout23.addWidget(self.tytul_tooltip2)
        self.verticalLayout_27.addLayout(self.hboxlayout23)
        self.hboxlayout24 = QtWidgets.QHBoxLayout()
        self.hboxlayout24.setObjectName("hboxlayout24")
        self.label3 = QtWidgets.QLabel(self.mGroupBox_8)
        self.label3.setObjectName("label3")
        self.hboxlayout24.addWidget(self.label3)
        self.mLineEdit3 = QgsFilterLineEdit(self.mGroupBox_8)
        self.mLineEdit3.setProperty("qgisRelation", "")
        self.mLineEdit3.setObjectName("mLineEdit3")
        self.hboxlayout24.addWidget(self.mLineEdit3)
        self.tytul_tooltip3 = QtWidgets.QLabel(self.mGroupBox_8)
        self.tytul_tooltip3.setToolTip("")
        self.tytul_tooltip3.setText("")
        self.tytul_tooltip3.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip3.setObjectName("tytul_tooltip3")
        self.hboxlayout24.addWidget(self.tytul_tooltip3)
        self.verticalLayout_27.addLayout(self.hboxlayout24)
        self.gridLayout_2.addWidget(self.mGroupBox_8, 8, 0, 1, 2)
        self.mGroupBox_9 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_9.sizePolicy().hasHeightForWidth())
        self.mGroupBox_9.setSizePolicy(sizePolicy)
        self.mGroupBox_9.setObjectName("mGroupBox_9")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.mGroupBox_9)
        self.verticalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.hboxlayout25 = QtWidgets.QHBoxLayout()
        self.hboxlayout25.setObjectName("hboxlayout25")
        self.label4 = QtWidgets.QLabel(self.mGroupBox_9)
        self.label4.setObjectName("label4")
        self.hboxlayout25.addWidget(self.label4)
        self.mLineEdit4 = QgsFilterLineEdit(self.mGroupBox_9)
        self.mLineEdit4.setProperty("qgisRelation", "")
        self.mLineEdit4.setObjectName("mLineEdit4")
        self.hboxlayout25.addWidget(self.mLineEdit4)
        self.tytul_tooltip4 = QtWidgets.QLabel(self.mGroupBox_9)
        self.tytul_tooltip4.setToolTip("")
        self.tytul_tooltip4.setText("")
        self.tytul_tooltip4.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip4.setObjectName("tytul_tooltip4")
        self.hboxlayout25.addWidget(self.tytul_tooltip4)
        self.verticalLayout_28.addLayout(self.hboxlayout25)
        self.hboxlayout26 = QtWidgets.QHBoxLayout()
        self.hboxlayout26.setObjectName("hboxlayout26")
        self.label5 = QtWidgets.QLabel(self.mGroupBox_9)
        self.label5.setObjectName("label5")
        self.hboxlayout26.addWidget(self.label5)
        self.mLineEdit5 = QgsFilterLineEdit(self.mGroupBox_9)
        self.mLineEdit5.setProperty("qgisRelation", "")
        self.mLineEdit5.setObjectName("mLineEdit5")
        self.hboxlayout26.addWidget(self.mLineEdit5)
        self.tytul_tooltip5 = QtWidgets.QLabel(self.mGroupBox_9)
        self.tytul_tooltip5.setToolTip("")
        self.tytul_tooltip5.setText("")
        self.tytul_tooltip5.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip5.setObjectName("tytul_tooltip5")
        self.hboxlayout26.addWidget(self.tytul_tooltip5)
        self.verticalLayout_28.addLayout(self.hboxlayout26)
        self.gridLayout_2.addWidget(self.mGroupBox_9, 9, 0, 1, 2)
        self.mGroupBox_10 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_10.sizePolicy().hasHeightForWidth())
        self.mGroupBox_10.setSizePolicy(sizePolicy)
        self.mGroupBox_10.setObjectName("mGroupBox_10")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.mGroupBox_10)
        self.verticalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.hboxlayout27 = QtWidgets.QHBoxLayout()
        self.hboxlayout27.setObjectName("hboxlayout27")
        self.label6 = QtWidgets.QLabel(self.mGroupBox_10)
        self.label6.setObjectName("label6")
        self.hboxlayout27.addWidget(self.label6)
        self.mLineEdit6 = QgsFilterLineEdit(self.mGroupBox_10)
        self.mLineEdit6.setProperty("qgisRelation", "")
        self.mLineEdit6.setObjectName("mLineEdit6")
        self.hboxlayout27.addWidget(self.mLineEdit6)
        self.tytul_tooltip6 = QtWidgets.QLabel(self.mGroupBox_10)
        self.tytul_tooltip6.setToolTip("")
        self.tytul_tooltip6.setText("")
        self.tytul_tooltip6.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip6.setObjectName("tytul_tooltip6")
        self.hboxlayout27.addWidget(self.tytul_tooltip6)
        self.verticalLayout_29.addLayout(self.hboxlayout27)
        self.hboxlayout28 = QtWidgets.QHBoxLayout()
        self.hboxlayout28.setObjectName("hboxlayout28")
        self.label7 = QtWidgets.QLabel(self.mGroupBox_10)
        self.label7.setObjectName("label7")
        self.hboxlayout28.addWidget(self.label7)
        self.mLineEdit7 = QgsFilterLineEdit(self.mGroupBox_10)
        self.mLineEdit7.setProperty("qgisRelation", "")
        self.mLineEdit7.setObjectName("mLineEdit7")
        self.hboxlayout28.addWidget(self.mLineEdit7)
        self.tytul_tooltip7 = QtWidgets.QLabel(self.mGroupBox_10)
        self.tytul_tooltip7.setToolTip("")
        self.tytul_tooltip7.setText("")
        self.tytul_tooltip7.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip7.setObjectName("tytul_tooltip7")
        self.hboxlayout28.addWidget(self.tytul_tooltip7)
        self.verticalLayout_29.addLayout(self.hboxlayout28)
        self.gridLayout_2.addWidget(self.mGroupBox_10, 10, 0, 1, 2)
        self.mGroupBox_11 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_11.sizePolicy().hasHeightForWidth())
        self.mGroupBox_11.setSizePolicy(sizePolicy)
        self.mGroupBox_11.setObjectName("mGroupBox_11")
        self.verticalLayout_210 = QtWidgets.QVBoxLayout(self.mGroupBox_11)
        self.verticalLayout_210.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_210.setObjectName("verticalLayout_210")
        self.hboxlayout29 = QtWidgets.QHBoxLayout()
        self.hboxlayout29.setObjectName("hboxlayout29")
        self.label8 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label8.setObjectName("label8")
        self.hboxlayout29.addWidget(self.label8)
        self.mLineEdit8 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit8.setProperty("qgisRelation", "")
        self.mLineEdit8.setObjectName("mLineEdit8")
        self.hboxlayout29.addWidget(self.mLineEdit8)
        self.tytul_tooltip8 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip8.setToolTip("")
        self.tytul_tooltip8.setText("")
        self.tytul_tooltip8.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip8.setObjectName("tytul_tooltip8")
        self.hboxlayout29.addWidget(self.tytul_tooltip8)
        self.verticalLayout_210.addLayout(self.hboxlayout29)
        self.hboxlayout30 = QtWidgets.QHBoxLayout()
        self.hboxlayout30.setObjectName("hboxlayout30")
        self.label9 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label9.setObjectName("label9")
        self.hboxlayout30.addWidget(self.label9)
        self.mLineEdit9 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit9.setProperty("qgisRelation", "")
        self.mLineEdit9.setObjectName("mLineEdit9")
        self.hboxlayout30.addWidget(self.mLineEdit9)
        self.tytul_tooltip9 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip9.setToolTip("")
        self.tytul_tooltip9.setText("")
        self.tytul_tooltip9.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip9.setObjectName("tytul_tooltip9")
        self.hboxlayout30.addWidget(self.tytul_tooltip9)
        self.verticalLayout_210.addLayout(self.hboxlayout30)
        self.hboxlayout31 = QtWidgets.QHBoxLayout()
        self.hboxlayout31.setObjectName("hboxlayout31")
        self.label10 = QtWidgets.QLabel(self.mGroupBox_11)
        self.label10.setObjectName("label10")
        self.hboxlayout31.addWidget(self.label10)
        self.mLineEdit10 = QgsFilterLineEdit(self.mGroupBox_11)
        self.mLineEdit10.setProperty("qgisRelation", "")
        self.mLineEdit10.setObjectName("mLineEdit10")
        self.hboxlayout31.addWidget(self.mLineEdit10)
        self.tytul_tooltip10 = QtWidgets.QLabel(self.mGroupBox_11)
        self.tytul_tooltip10.setToolTip("")
        self.tytul_tooltip10.setText("")
        self.tytul_tooltip10.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip10.setObjectName("tytul_tooltip10")
        self.hboxlayout31.addWidget(self.tytul_tooltip10)
        self.verticalLayout_210.addLayout(self.hboxlayout31)
        self.gridLayout_2.addWidget(self.mGroupBox_11, 11, 0, 1, 2)
        self.mGroupBox_12 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12.setSizePolicy(sizePolicy)
        self.mGroupBox_12.setObjectName("mGroupBox_12")
        self.verticalLayout_211 = QtWidgets.QVBoxLayout(self.mGroupBox_12)
        self.verticalLayout_211.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_211.setObjectName("verticalLayout_211")
        self.hboxlayout32 = QtWidgets.QHBoxLayout()
        self.hboxlayout32.setObjectName("hboxlayout32")
        self.label11 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label11.setObjectName("label11")
        self.hboxlayout32.addWidget(self.label11)
        self.mLineEdit11 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit11.setProperty("qgisRelation", "")
        self.mLineEdit11.setObjectName("mLineEdit11")
        self.hboxlayout32.addWidget(self.mLineEdit11)
        self.tytul_tooltip11 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip11.setToolTip("")
        self.tytul_tooltip11.setText("")
        self.tytul_tooltip11.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip11.setObjectName("tytul_tooltip11")
        self.hboxlayout32.addWidget(self.tytul_tooltip11)
        self.verticalLayout_211.addLayout(self.hboxlayout32)
        self.hboxlayout33 = QtWidgets.QHBoxLayout()
        self.hboxlayout33.setObjectName("hboxlayout33")
        self.label12 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label12.setObjectName("label12")
        self.hboxlayout33.addWidget(self.label12)
        self.mLineEdit12 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit12.setProperty("qgisRelation", "")
        self.mLineEdit12.setObjectName("mLineEdit12")
        self.hboxlayout33.addWidget(self.mLineEdit12)
        self.tytul_tooltip12 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip12.setToolTip("")
        self.tytul_tooltip12.setText("")
        self.tytul_tooltip12.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip12.setObjectName("tytul_tooltip12")
        self.hboxlayout33.addWidget(self.tytul_tooltip12)
        self.verticalLayout_211.addLayout(self.hboxlayout33)
        self.hboxlayout34 = QtWidgets.QHBoxLayout()
        self.hboxlayout34.setObjectName("hboxlayout34")
        self.label13 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label13.setObjectName("label13")
        self.hboxlayout34.addWidget(self.label13)
        self.mLineEdit13 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit13.setProperty("qgisRelation", "")
        self.mLineEdit13.setObjectName("mLineEdit13")
        self.hboxlayout34.addWidget(self.mLineEdit13)
        self.tytul_tooltip13 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip13.setToolTip("")
        self.tytul_tooltip13.setText("")
        self.tytul_tooltip13.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip13.setObjectName("tytul_tooltip13")
        self.hboxlayout34.addWidget(self.tytul_tooltip13)
        self.verticalLayout_211.addLayout(self.hboxlayout34)
        self.hboxlayout35 = QtWidgets.QHBoxLayout()
        self.hboxlayout35.setObjectName("hboxlayout35")
        self.label14 = QtWidgets.QLabel(self.mGroupBox_12)
        self.label14.setObjectName("label14")
        self.hboxlayout35.addWidget(self.label14)
        self.mLineEdit14 = QgsFilterLineEdit(self.mGroupBox_12)
        self.mLineEdit14.setProperty("qgisRelation", "")
        self.mLineEdit14.setObjectName("mLineEdit14")
        self.hboxlayout35.addWidget(self.mLineEdit14)
        self.tytul_tooltip14 = QtWidgets.QLabel(self.mGroupBox_12)
        self.tytul_tooltip14.setToolTip("")
        self.tytul_tooltip14.setText("")
        self.tytul_tooltip14.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip14.setObjectName("tytul_tooltip14")
        self.hboxlayout35.addWidget(self.tytul_tooltip14)
        self.verticalLayout_211.addLayout(self.hboxlayout35)
        self.mGroupBox_12_5 = QgsCollapsibleGroupBox(self.mGroupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12_5.setSizePolicy(sizePolicy)
        self.mGroupBox_12_5.setObjectName("mGroupBox_12_5")
        self.verticalLayout_212 = QtWidgets.QVBoxLayout(self.mGroupBox_12_5)
        self.verticalLayout_212.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_212.setObjectName("verticalLayout_212")
        self.hboxlayout36 = QtWidgets.QHBoxLayout()
        self.hboxlayout36.setObjectName("hboxlayout36")
        self.label15 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.label15.setObjectName("label15")
        self.hboxlayout36.addWidget(self.label15)
        self.mLineEdit15 = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.mLineEdit15.setProperty("qgisRelation", "")
        self.mLineEdit15.setObjectName("mLineEdit15")
        self.hboxlayout36.addWidget(self.mLineEdit15)
        self.tytul_tooltip15 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.tytul_tooltip15.setToolTip("")
        self.tytul_tooltip15.setText("")
        self.tytul_tooltip15.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip15.setObjectName("tytul_tooltip15")
        self.hboxlayout36.addWidget(self.tytul_tooltip15)
        self.verticalLayout_212.addLayout(self.hboxlayout36)
        self.hboxlayout37 = QtWidgets.QHBoxLayout()
        self.hboxlayout37.setObjectName("hboxlayout37")
        self.label16 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.label16.setObjectName("label16")
        self.hboxlayout37.addWidget(self.label16)
        self.mLineEdit16 = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.mLineEdit16.setProperty("qgisRelation", "")
        self.mLineEdit16.setObjectName("mLineEdit16")
        self.hboxlayout37.addWidget(self.mLineEdit16)
        self.tytul_tooltip16 = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.tytul_tooltip16.setToolTip("")
        self.tytul_tooltip16.setText("")
        self.tytul_tooltip16.setPixmap(QtGui.QPixmap("../../../../img/info1.png"))
        self.tytul_tooltip16.setObjectName("tytul_tooltip16")
        self.hboxlayout37.addWidget(self.tytul_tooltip16)
        self.verticalLayout_212.addLayout(self.hboxlayout37)
        self.verticalLayout_211.addWidget(self.mGroupBox_12_5)
        self.gridLayout_2.addWidget(self.mGroupBox_12, 12, 0, 1, 2)
        self.form_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.form_scrollArea)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.send_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send_lbl.setFont(font)
        self.send_lbl.setObjectName("send_lbl")
        self.verticalLayout.addWidget(self.send_lbl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.server_btn = QtWidgets.QPushButton(Dialog)
        self.server_btn.setEnabled(False)
        self.server_btn.setObjectName("server_btn")
        self.gridLayout.addWidget(self.server_btn, 0, 1, 1, 1)
        self.email_btn = QtWidgets.QPushButton(Dialog)
        self.email_btn.setEnabled(False)
        self.email_btn.setObjectName("email_btn")
        self.gridLayout.addWidget(self.email_btn, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_3.addWidget(self.prev_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.validateAndSave_btn = QtWidgets.QPushButton(Dialog)
        self.validateAndSave_btn.setObjectName("validateAndSave_btn")
        self.horizontalLayout_3.addWidget(self.validateAndSave_btn)
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setEnabled(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Metadane"))
        self.existingMetadata_lbl.setText(_translate("Dialog", "Aktualizuj plik z metadanymi (opcjonalne)    "))
        self.chooseFile_widget.setText(_translate("Dialog", "..."))
        self.file_lbl.setText(_translate("Dialog", "..."))
        self.addSet_lbl.setText(_translate("Dialog", "Wybierz plik GML dla zbioru APP (opcjonalne)"))
        self.titleForm_lbl.setText(_translate("Dialog", "Formularz metadanych:"))
        self.mGroupBox.setTitle(_translate("Dialog", "Identyfikacja*"))
        self.e1_lbl.setText(_translate("Dialog", "Tytuł zbioru*"))
        self.e1_tooltip.setToolTip(_translate("Dialog", "Nazwa zbioru danych przestrzennych. \n"
"\n"
"Nazwa zbioru danych przestrzennych musi być skonstruowana zgodnie ze wzorem dla:\n"
"1)    planu zagospodarowania przestrzennego województwa: „Zbiór danych dla planu zagospodarowania przestrzennego województwa <nazwa jednostki podziału administracyjnego kraju>”;\n"
"2)    studium uwarunkowań i kierunków zagospodarowania przestrzennego: „Zbiór danych dla studium uwarunkowań i kierunków zagospodarowania przestrzennego <typ jednostki podziału administracyjnego kraju> <nazwa jednostki podziału administracyjnego kraju>”,\n"
"3)    miejscowych planów, w tym miejscowych planów zagospodarowania przestrzennego, miejscowych planów odbudowy oraz miejscowych planów rewitalizacji: „Zbiór danych dla miejscowych planów <typ jednostki podziału administracyjnego kraju> <nazwa jednostki podziału administracyjnego kraju>”.\n"
""))
        self.e2_lbl.setText(_translate("Dialog", "Streszczenie*"))
        self.e2_tooltip.setToolTip(_translate("Dialog", "Zwięzły opis zawartości zbioru danych."))
        self.e3_lbl.setText(_translate("Dialog", "Typ zbioru*"))
        self.e3_tooltip.setToolTip(_translate("Dialog", "Typ zbioru danych opisywanego przez metadane. \n"
"\n"
"Wartości elementu metadanych zawsze jest równa: zbiór danych („dataset”).\n"
""))
        self.e4_lbl.setText(_translate("Dialog", "Adres zbioru"))
        self.e4_tooltip.setToolTip(_translate("Dialog", "Adres zbioru danych określa odnośnik (odnośniki) do tego zbioru lub odnośnik do dodatkowych informacji na jego temat.\n"
"\n"
"Adres zbioru musi być wyspecyfikowany w formie adresu URI:\n"
"1)    usługi sieciowej udostępniającej zbiór danych;\n"
"2)    strony internetowej zawierającej dodatkowe informacje na temat zbioru danych, lub jeżeli jest on niedostępny;\n"
"3)    strony internetowej organizacji odpowiedzialnej za zbiór danych.\n"
""))
        self.e5_lbl.setText(_translate("Dialog", "Unikalny identyfikator zbioru*"))
        self.e5_tooltip.setToolTip(_translate("Dialog", "Wartość, o której mowa w §4 rozporządzenia, identyfikująca dany zbiór danych w unikalny sposób."))
        self.e6_lbl.setText(_translate("Dialog", "Język zbioru*"))
        self.e6_tooltip.setToolTip(_translate("Dialog", "Język stosowany w zbiorze danych."))
        self.e7_lbl.setText(_translate("Dialog", "Kodowanie znaków"))
        self.e7_cmbbx.setItemText(1, _translate("Dialog", "ucs2"))
        self.e7_cmbbx.setItemText(2, _translate("Dialog", "ucs4"))
        self.e7_cmbbx.setItemText(3, _translate("Dialog", "utf7"))
        self.e7_cmbbx.setItemText(4, _translate("Dialog", "utf8"))
        self.e7_cmbbx.setItemText(5, _translate("Dialog", "utf16"))
        self.e7_cmbbx.setItemText(6, _translate("Dialog", "8859część1"))
        self.e7_cmbbx.setItemText(7, _translate("Dialog", "8859część2"))
        self.e7_cmbbx.setItemText(8, _translate("Dialog", "8859część3"))
        self.e7_cmbbx.setItemText(9, _translate("Dialog", "8859część4"))
        self.e7_cmbbx.setItemText(10, _translate("Dialog", "8859część5"))
        self.e7_cmbbx.setItemText(11, _translate("Dialog", "8859część9"))
        self.e7_cmbbx.setItemText(12, _translate("Dialog", "8859część10"))
        self.e7_cmbbx.setItemText(13, _translate("Dialog", "8859część13"))
        self.e7_cmbbx.setItemText(14, _translate("Dialog", "8859część14"))
        self.e7_cmbbx.setItemText(15, _translate("Dialog", "8859część15"))
        self.e7_cmbbx.setItemText(16, _translate("Dialog", "8859część16"))
        self.e7_cmbbx.setItemText(17, _translate("Dialog", "usAscii"))
        self.e7_cmbbx.setItemText(18, _translate("Dialog", "ebcdic"))
        self.e7_tooltip.setToolTip(_translate("Dialog", "Nazwa sposobu kodowania znaków (informacji tekstowej) użytego w zbiorze danych."))
        self.mGroupBox_2.setTitle(_translate("Dialog", "Klasyfikacja danych przestrzennych*"))
        self.e8_lbl.setText(_translate("Dialog", "Kategoria tematyczna*"))
        self.e8_lineEdit.setText(_translate("Dialog", "Planowanie/Kataster"))
        self.e8_tooltip.setToolTip(_translate("Dialog", "Klasyfikacja zbioru danych przestrzennych, opisana z użyciem wysokiego poziomu schematu klasyfikacyjnego wspomagającego grupowanie i ukierunkowane tematycznie wyszukiwanie dostępnych zbiorów danych przestrzennych.\n"
"\n"
"Wartość elementu metadanych zawsze jest równa: „Planowanie/Kataster” („planningCadastre”).\n"
""))
        self.qgsCollapsibleGroupBox.setTitle(_translate("Dialog", "Słowo kluczowe*"))
        self.e9_lbl.setText(_translate("Dialog", "Wartość słowa kluczowego*"))
        self.e9_tooltip.setToolTip(_translate("Dialog", "Słowo potocznie używane, słowo sformalizowane lub fraza stosowana do opisu danego tematu; podczas gdy kategorie tematyczne są zbyt ogólne dla zapytań szczegółowych, słowa kluczowe pomagają uszczegółowić wyszukiwanie pełnych tekstów oraz umożliwiają wyszukiwanie strukturalnych słów kluczowych.\n"
"\n"
"Obowiązkowo należy podać  słowa kluczowe:\n"
"•    opisujące odpowiedni temat danych przestrzennych i pozyskane z ogólnego wielojęzycznego tezaurusa środowiskowego (GEMET). Słowo to musi być równe: „Zagospodarowanie przestrzenne”,\n"
"•    opisujące poziom administracyjny, który zbiór danych obejmuje (zakres przestrzenny),\n"
"•    opisujące typ zbioru danych, w formie neutralnego językowo słowa równego: „PlannedLandUse”.\n"
"•    opisujące poziom jednostki administracyjnej objętej aktem planowania przestrzennego. Słowo to musi być równe zdefiniowanym w liście kodowej „Poziom planu zagospodarowania przestrzennego” zdefiniowanej w tabeli 2.7 w załączniku nr 1 do rozporządzenia.\n"
""))
        self.e9_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e9_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e9_listWidget.setSortingEnabled(False)
        __sortingEnabled = self.e9_listWidget.isSortingEnabled()
        self.e9_listWidget.setSortingEnabled(False)
        item = self.e9_listWidget.item(0)
        item.setText(_translate("Dialog", "Zagospodarowanie przestrzenne"))
        item = self.e9_listWidget.item(1)
        item.setText(_translate("Dialog", "<zakres przestrzenny>"))
        item = self.e9_listWidget.item(2)
        item.setText(_translate("Dialog", "PlannedLandUse"))
        item = self.e9_listWidget.item(3)
        item.setText(_translate("Dialog", "<poziom planu zagosp. przetrz.>"))
        self.e9_listWidget.setSortingEnabled(__sortingEnabled)
        self.e10_lbl.setText(_translate("Dialog", "Standardowy słownik źródłowy"))
        self.mGroupBox_4.setTitle(_translate("Dialog", "Położenie geograficzne*"))
        self.e11_lbl.setText(_translate("Dialog", "Geograficzny prostokąt ograniczający*"))
        self.e11_tooltip.setToolTip(_translate("Dialog", "Zasięg zbioru w przestrzeni geograficznej, wyrażony za pomocą prostokąta ograniczającego, opisanego za pomocą południków granicy zachodniej i granicy wschodniej obszaru oraz równoleżników granicy południowej i granicy północnej wyrażonych w częściach dziesiętnych stopnia, z dokładnością do co najmniej czterech cyfr dziesiętnych.\n"
"\n"
"Jeżeli zbiór danych charakteryzuje się brakiem ciągłości przestrzennej, można określić więcej niż jeden prostokąt ograniczający.\n"
"\n"
"Współrzędne należy podać w Światowym Systemie Geodezyjnym 1984 (WGS84).\n"
""))
        self.e11_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e11_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e11_listWidget.setSortingEnabled(False)
        self.e12_lbl.setText(_translate("Dialog", "System odniesienia za pomocą współrzędnych*"))
        self.e12_tooltip.setToolTip(_translate("Dialog", "System odniesienia za pomocą współrzędnych zastosowany dla zbioru danych.\n"
"\n"
"Należy podać identyfikator systemu odniesienia w EPSG Geodetic Parameter Registry.\n"
""))
        self.e12_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e12_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e12_listWidget.setSortingEnabled(False)
        self.mGroupBox_5.setTitle(_translate("Dialog", "Odniesienie czasowe*"))
        self.e13_lbl.setText(_translate("Dialog", "Data utworzenia*"))
        self.e13_cmbbx.setItemText(0, _translate("Dialog", "utworzenie"))
        self.e13_cmbbx.setItemText(1, _translate("Dialog", "publikacja"))
        self.e13_cmbbx.setItemText(2, _translate("Dialog", "przegląd"))
        self.e13_tooltip.setToolTip(_translate("Dialog", "Data utworzenia zbioru.\n"
"\n"
"Wartość elementu musi  wyrażać co najmniej datę dzienną, która  może być rozszerzona o wskazanie czasu (godzina, minuta, sekunda).\n"
""))
        self.e14_lbl.setText(_translate("Dialog", "Data opublikowania"))
        self.e14_cmbbx.setItemText(0, _translate("Dialog", "utworzenie"))
        self.e14_cmbbx.setItemText(1, _translate("Dialog", "publikacja"))
        self.e14_cmbbx.setItemText(2, _translate("Dialog", "przegląd"))
        self.e14_tooltip.setToolTip(_translate("Dialog", "Data udostępnienia zbioru danych za pośrednictwem usług sieciowych.\n"
"Wartość elementu musi  wyrażać co najmniej datę dzienną, która  może być rozszerzona o wskazanie czasu (godzina, minuta, sekunda).\n"
""))
        self.mGroupBox_6.setTitle(_translate("Dialog", "Jakość i ważność*"))
        self.e15_lbl.setText(_translate("Dialog", "Pochodzenie*"))
        self.e15_tooltip.setToolTip(_translate("Dialog", "Opis historii procesu tworzenia lub ogólnej jakości zbioru danych przestrzennych. W stosownych przypadkach może zawierać stwierdzenie, czy zbiór danych był przedmiotem procesu kontroli lub oceny jakości, czy stanowi wersję urzędową i czy posiada moc prawną."))
        self.e16_lbl.setText(_translate("Dialog", "Rozdzielczość przestrzenna*"))
        self.e16_tooltip.setToolTip(_translate("Dialog", "Wielkość opisująca poziom szczegółowości zbioru danych, podawana jako skala równorzędna, wyrażona za pomocą liczby całkowitej stanowiącej mianownik skali."))
        self.e12_add_btn1.setText(_translate("Dialog", "Dodaj"))
        self.e12_remove_btn1.setText(_translate("Dialog", "Usuń"))
        self.e12_listWidget1.setSortingEnabled(False)
        self.e17_lbl.setText(_translate("Dialog", "Typ reprezentacji przestrzennej*"))
        self.e17_lineEdit.setText(_translate("Dialog", "Vector; Grid"))
        self.e17_tooltip.setToolTip(_translate("Dialog", "Metoda przestrzennej reprezentacji danych zbioru.\n"
"\n"
"Element metadanych zawsze przyjmuje wartości: wektor „Vector” oraz raster „Grid”.\n"
"\n"
""))
        self.mGroupBox_7.setTitle(_translate("Dialog", "Zgodność"))
        self.label.setText(_translate("Dialog", "Specyfikacja"))
        self.label1.setText(_translate("Dialog", "Stopień"))
        self.mGroupBox_8.setTitle(_translate("Dialog", "Wymogi dotyczące dostępu i użytkowania"))
        self.label2.setText(_translate("Dialog", "Warunki dotyczące dostępu i użytkowania"))
        self.label3.setText(_translate("Dialog", "Ograniczenia w publicznym dostępie"))
        self.mGroupBox_9.setTitle(_translate("Dialog", "Organizacje odpowiedzialne"))
        self.label4.setText(_translate("Dialog", "Jednostka odpowiedzialna"))
        self.label5.setText(_translate("Dialog", "Rola jednostki odpowiedzialnej"))
        self.mGroupBox_10.setTitle(_translate("Dialog", "Kodowanie"))
        self.label6.setText(_translate("Dialog", "Nazwa formatu"))
        self.label7.setText(_translate("Dialog", "Wersja formatu"))
        self.mGroupBox_11.setTitle(_translate("Dialog", "Informacje o utrzymaniu zbioru"))
        self.label8.setText(_translate("Dialog", "Częstotliwość aktualizacji"))
        self.label9.setText(_translate("Dialog", "Informacja o szczegółowych wymaganiach dotyczących utrzymania"))
        self.label10.setText(_translate("Dialog", "Zakres danych"))
        self.mGroupBox_12.setTitle(_translate("Dialog", "Metadane na temat metadanych"))
        self.label11.setText(_translate("Dialog", "Punkt kontaktowy metadanych"))
        self.label12.setText(_translate("Dialog", "Data metadanych"))
        self.label13.setText(_translate("Dialog", "Język metadanych"))
        self.label14.setText(_translate("Dialog", "Unikalny identyfikator rekordu (pliku) metadanych"))
        self.mGroupBox_12_5.setTitle(_translate("Dialog", "Standard metadanych"))
        self.label15.setText(_translate("Dialog", "Nazwa standardu metadanych"))
        self.label16.setText(_translate("Dialog", "Wersja standardu metadanych"))
        self.send_lbl.setText(_translate("Dialog", "Wybierz, gdzie chcesz wysłać plik z metadanymi (opcjonalne):"))
        self.server_btn.setText(_translate("Dialog", "Wyślij na serwer katalogowy"))
        self.email_btn.setText(_translate("Dialog", "Wyślij na adres email"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.validateAndSave_btn.setText(_translate("Dialog", "Waliduj/zapisz"))
        self.close_btn.setText(_translate("Dialog", "Zakończ"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsdatetimeedit import QgsDateTimeEdit
from qgsfilewidget import QgsFileWidget
from qgsfilterlineedit import QgsFilterLineEdit
