# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'walidacja_gmlxml_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        font = QtGui.QFont()
        font.setKerning(True)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.validateGML_checkBox = QtWidgets.QCheckBox(Dialog)
        self.validateGML_checkBox.setChecked(True)
        self.validateGML_checkBox.setObjectName("validateGML_checkBox")
        self.horizontalLayout.addWidget(self.validateGML_checkBox)
        self.chooseGML_widget = QgsFileWidget(Dialog)
        self.chooseGML_widget.setObjectName("chooseGML_widget")
        self.horizontalLayout.addWidget(self.chooseGML_widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setGML_radioButton = QtWidgets.QRadioButton(Dialog)
        self.setGML_radioButton.setChecked(True)
        self.setGML_radioButton.setObjectName("setGML_radioButton")
        self.horizontalLayout_2.addWidget(self.setGML_radioButton)
        self.appGML_radioButton = QtWidgets.QRadioButton(Dialog)
        self.appGML_radioButton.setObjectName("appGML_radioButton")
        self.horizontalLayout_2.addWidget(self.appGML_radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.validateXML_checkBox = QtWidgets.QCheckBox(Dialog)
        self.validateXML_checkBox.setChecked(False)
        self.validateXML_checkBox.setObjectName("validateXML_checkBox")
        self.horizontalLayout_3.addWidget(self.validateXML_checkBox)
        self.chooseXML_widget = QgsFileWidget(Dialog)
        self.chooseXML_widget.setEnabled(False)
        self.chooseXML_widget.setObjectName("chooseXML_widget")
        self.horizontalLayout_3.addWidget(self.chooseXML_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.validate_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validate_lbl.setFont(font)
        self.validate_lbl.setObjectName("validate_lbl")
        self.verticalLayout.addWidget(self.validate_lbl)
        self.validate_scrollArea = QtWidgets.QScrollArea(Dialog)
        self.validate_scrollArea.setWidgetResizable(True)
        self.validate_scrollArea.setObjectName("validate_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 484, 306))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.validationInfo_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.validationInfo_lbl.setWordWrap(True)
        self.validationInfo_lbl.setObjectName("validationInfo_lbl")
        self.verticalLayout_2.addWidget(self.validationInfo_lbl)
        self.validate_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.validate_scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.nameFile_lbl = QtWidgets.QLabel(Dialog)
        self.nameFile_lbl.setObjectName("nameFile_lbl")
        self.horizontalLayout_4.addWidget(self.nameFile_lbl)
        self.export_btn = QtWidgets.QPushButton(Dialog)
        self.export_btn.setEnabled(True)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_4.addWidget(self.export_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_5.addWidget(self.prev_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.validate_btn = QtWidgets.QPushButton(Dialog)
        self.validate_btn.setObjectName("validate_btn")
        self.horizontalLayout_5.addWidget(self.validate_btn)
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_5.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Walidacja plików GML / XML"))
        self.validateGML_checkBox.setText(_translate("Dialog", "Walidacja GML"))
        self.setGML_radioButton.setText(_translate("Dialog", "GML dla zbioru APP"))
        self.appGML_radioButton.setText(_translate("Dialog", "GML dla APP"))
        self.validateXML_checkBox.setText(_translate("Dialog", "Walidacja XML (metadane)"))
        self.validate_lbl.setText(_translate("Dialog", "Walidacja - progres"))
        self.validationInfo_lbl.setText(_translate("Dialog", "Tu pojawi się informacja o sukcesie lub lista błędów z możliwością eksportu."))
        self.nameFile_lbl.setText(_translate("Dialog", "app12_220520123445.txt"))
        self.export_btn.setText(_translate("Dialog", "Eksportuj"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.validate_btn.setText(_translate("Dialog", "Waliduj"))
        self.close_btn.setToolTip(_translate("Dialog", "<html><head/><body><p>Przycisk <span style=\" font-style:italic;\">Zakończ</span> zakończy działanie wtyczki</p></body></html>"))
        self.close_btn.setText(_translate("Dialog", "Zakończ"))
from qgsfilewidget import QgsFileWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
